const escape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function intakePage(env){return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>МИРА — запрос подключения</title>
<style>body{font:18px/1.5 system-ui;margin:0;background:#f5f3ec;color:#152f2b}main{max-width:620px;margin:40px auto;padding:24px}h1{font-size:2rem}label{display:block;margin-top:16px}input:not([type=checkbox]){display:block;box-sizing:border-box;width:100%;font:inherit;padding:12px;border:1px solid #63736b;border-radius:6px}button{font:inherit;padding:12px 18px;margin:16px 0;background:#183d35;color:white;border:0;border-radius:6px}button:disabled{opacity:.5}a{color:#185d49}#message{white-space:pre-wrap;overflow-wrap:anywhere}small{display:block}input[type=checkbox]{width:22px;height:22px;vertical-align:middle}</style>
<script src="/mira/request/client.mjs" type="module"></script><script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script></head><body><main>
<a href="https://wegc.fund/mira/start/">МИРА</a><h1>Подключить агентство</h1><p>Оставьте контакты агентства. Мы свяжемся с вами по рабочему email и обсудим условия сотрудничества.</p>
${env.PUBLIC_INTAKE_SUBMISSIONS_PAUSED==='true'?'<p role="status">Приём новых запросов временно приостановлен. Статус отправленной заявки можно проверить ниже.</p>':''}
<form id="request" ${env.PUBLIC_INTAKE_SUBMISSIONS_PAUSED==='true'?'hidden':''} data-paused="${env.PUBLIC_INTAKE_SUBMISSIONS_PAUSED==='true'}" data-consent="${escape(env.PUBLIC_INTAKE_PRIVACY_VERSION)}">
<label>Агентство<input name="company" required minlength="2" maxlength="160" autocomplete="organization"></label>
<label>Город<input name="city" required minlength="2" maxlength="120" autocomplete="address-level2"></label>
<label>Ваше имя<input name="name" required minlength="2" maxlength="120" autocomplete="name"></label>
<label>Рабочий email<input name="email" type="email" required maxlength="254" autocomplete="email"></label>
<label><input name="consent" type="checkbox" required> Согласен с обработкой данных для ответа на запрос по <a href="${escape(env.PUBLIC_INTAKE_PRIVACY_NOTICE_URL)}" target="_blank" rel="noopener noreferrer">уведомлению о конфиденциальности</a>.</label>
<div class="cf-turnstile" data-sitekey="${escape(env.TURNSTILE_SITE_KEY)}" data-action="mira_intake" data-language="ru" data-appearance="interaction-only"></div>
<button id="send" type="submit">Отправить запрос</button></form>
<p id="message" role="status" aria-live="polite"></p><button id="refresh" type="button" hidden>Проверить статус</button>
<noscript>Для отправки заявки включите JavaScript или напишите нам: <a href="mailto:post@wegc.fund">post@wegc.fund</a>.</noscript>
</main></body></html>`;}
export const intakeClient=String.raw`
const form=document.getElementById('request'),message=document.getElementById('message'),send=document.getElementById('send'),refresh=document.getElementById('refresh');
const storageKey='mira-intake-receipt-v1';let saved;
try{saved=JSON.parse(sessionStorage.getItem(storageKey)||'null');}catch{}
if(!saved||!/^\w{8}-[\w-]{27}$/.test(saved.key||'')||! /^[0-9a-f]{64}$/.test(saved.token||'')){
 saved={key:crypto.randomUUID(),token:Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join(''),id:null};
}
function retain(){try{sessionStorage.setItem(storageKey,JSON.stringify(saved));return true;}catch{return false;}}
const labels={received:'Получен',review:'На рассмотрении',needs_information:'Нужно уточнение',responded:'Есть ответ',closed:'Обработка завершена'};
function show(data){saved.id=data.id;retain();form.hidden=true;refresh.hidden=false;message.textContent='Спасибо! Заявка принята. Мы свяжемся с вами по указанному email.'+'\nНомер заявки: '+data.id+'\nСтатус: '+(labels[data.status]||data.status)+(data.response?'\nСообщение команды МИРА: '+data.response:'');}
async function api(path,payload){const r=await fetch('/mira/request/'+path,{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json','Authorization':'Bearer '+saved.token,'Idempotency-Key':saved.key},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error||'request_failed');return data;}
function failure(e){const known={intake_rate_limit:'Слишком много попыток. Повторите позже.',challenge_rejected:'Пройдите проверку ещё раз.',intake_disabled:'Приём временно закрыт.',intake_submissions_paused:'Приём новых запросов временно приостановлен. Уже сохранённые квитанции доступны.',intake_operator_unavailable:'Приём временно недоступен. Попробуйте позже.',receipt_erased:'Данные запроса удалены. Повторная отправка этой квитанции отключена.',receipt_not_found:'Квитанция не найдена. Не создавайте повторный запрос, пока не проверен результат.',idempotency_payload_mismatch:'Эта попытка уже связана с другими данными. Повторная заявка не создана.'};message.textContent=known[e.message]||'Не удалось подтвердить результат. Повторите с теми же данными: повторная попытка не создаст дубликат.';}
form.addEventListener('submit',async e=>{e.preventDefault();if(form.dataset.paused==='true'){failure(Error('intake_submissions_paused'));return;}if(!form.reportValidity())return;const values=new FormData(form);const challenge=values.get('cf-turnstile-response');if(!challenge){message.textContent='Сначала пройдите проверку безопасности.';return;}send.disabled=true;retain();try{show(await api('submit',{company:values.get('company'),city:values.get('city'),name:values.get('name'),email:values.get('email'),consent_version:form.dataset.consent,challenge}));}catch(error){failure(error);window.turnstile?.reset();}finally{send.disabled=false;}});
refresh.addEventListener('click',async()=>{refresh.disabled=true;try{show(await api('status',{id:saved.id}));}catch(error){failure(error);}finally{refresh.disabled=false;}});
if(saved.id){form.hidden=true;refresh.hidden=false;message.textContent='Ваша заявка принята. Мы свяжемся с вами по рабочему email. Номер заявки: '+saved.id+'.';}
`;

export const intakePrivacyPage=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>МИРА — данные запроса</title><style>body{font:18px/1.6 system-ui;background:#f5f3ec;color:#173a30;margin:0}main{max-width:760px;margin:auto;padding:32px 24px}h1{font-size:2.2rem}h2{font-size:1.35rem;margin-top:32px}a{color:#185d49}address{font-style:normal}small{color:#53675d}</style></head><body><main><a href="/mira/request/">← К запросу подключения</a><h1>Данные вашего запроса</h1><small>24 сентября 2026 · mira-public-2026-09-24-v1</small><p>Это уведомление относится к открытому запросу подключения агентства к МИРА. Для отправки не требуется приглашение или вход. Email в этой форме не подтверждается автоматически.</p>
<h2>Кто принимает запрос</h2><address>WEST EAST TRADE GROUP PTE. LTD., UEN 202505772C.<br>110 Robinson Road, #08-00, ERH Building, Singapore 068901.</address><p>Вопросы о данных и отзыв согласия: <a href="mailto:dpo@wegc.fund">dpo@wegc.fund</a>. Связь с командой: <a href="mailto:post@wegc.fund">post@wegc.fund</a>.</p>
<h2>Какие данные и зачем</h2><p>Мы сохраняем название агентства, город, имя представителя и рабочий email, чтобы рассмотреть обращение и связаться по вопросу подключения. Также сохраняются номер запроса, время, версия согласия, технические идентификаторы повтора, назначение оператора, статусы и опубликованные ответы. Паспорт, банковские реквизиты и сведения о покупателях в этой форме не нужны.</p><p>Отправка не заключает договор, не активирует агентство и не регистрирует покупателя у застройщика. Данные запроса не отправляются застройщикам автоматически. Форма не подписывает на рекламу.</p>
<h2>Кто имеет доступ</h2><p>Контакты и историю видят уполномоченные операторы МИРА через защищённый вход. В вашей квитанции доступны номер, статус и опубликованный ответ; доступ к ней сохраняется в вашем браузере. Не передавайте доступ к заявке посторонним.</p><p>Для серверной обработки используются Cloudflare Workers и D1, для защиты от автоматических запросов — Cloudflare Turnstile, для входа оператора — Cloudflare Access. Turnstile обрабатывает технические данные устройства и соединения; сервер использует IP для проверки и ограничения частоты. В прикладной таблице ограничений сохраняется часовой HMAC-идентификатор вместо IP, старые записи очищаются.</p><p>Для текущей базы наблюдается APAC/SIN (Сингапур); это не гарантия географии всей сети Cloudflare, служебных журналов или копий. Обработка осуществляется за пределами России.</p>
<h2>Срок хранения и удаление</h2><p>Обращения без заключённого договора хранятся до 24 месяцев с последней активности по запросу, затем автоматически удаляются вместе с текстами ответов и историей рассмотрения. По подтверждённому обращению удаление может выполнить оператор раньше. На 31 день остаётся техническая отметка без имени, email, компании и текстов, чтобы закрыть старую квитанцию и предотвратить восстановление удалённого запроса.</p><p>Восстановительные копии D1 могут сохраняться до 30 дней. Они не используются для обычной работы. При восстановлении удаление по сохранённым отметкам применяется до возобновления доступа. Локальные эксплуатационные копии ограничены тем же сроком.</p>
<h2>Ваши обращения</h2><p>Напишите на <a href="mailto:dpo@wegc.fund?subject=MIRA%20public%20request%20data">dpo@wegc.fund</a> с номером запроса для получения сведений, исправления, удаления или отзыва согласия. Перед выполнением мы проверим принадлежность запроса; одного непроверенного email недостаточно. После удаления продолжить рассмотрение этой заявки нельзя.</p>
<h2>Как вы даёте согласие</h2><p>Перед отправкой вы самостоятельно отмечаете отдельный, изначально выключенный флажок. Вместе с запросом сохраняются версия уведомления и время получения. После отправки вы увидите подтверждение приёма заявки. Команда МИРА связывается с вами по указанному рабочему email по поводу обращения.</p><p><a href="/mira/request/">Вернуться к форме</a></p></main></body></html>`;
