export const researchHTML=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>МИРА — базы исследований</title><style>body{font:17px/1.5 system-ui;color:#15342d;background:#f6f4ee;margin:0;overflow-wrap:anywhere}main{max-width:1100px;margin:auto;padding:24px}button,input,select{font:inherit;padding:10px;margin:6px 8px 6px 0}button{cursor:pointer}article{background:white;margin:12px 0;padding:16px;border:1px solid #ccd5d0;border-radius:8px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}#status{min-height:1.5em}a{color:#145b49}details{padding:8px 0}button:disabled{opacity:.5}*{box-sizing:border-box}form{display:flex;flex-wrap:wrap;align-items:end;gap:8px}label{min-width:0;max-width:100%}input{max-width:100%}@media(max-width:600px){main{padding:16px}h2{font-size:1.3rem}input{display:block;width:100%}}</style><script type="module" src="/mira/research/client.mjs"></script></head><body><main><a href="/mira/pilot.html">В кабинет</a><h1>Базы МИРА</h1><p>Исследовательские записи агентств и застройщиков. Наличие контакта или связи с проектом не означает действующий договор или доступный юнит. Актуальные предложения запрашиваются у застройщика.</p><p id="summary"></p><form id="search"><label>База <select id="kind"><option value="agency">Агентства</option><option value="developer">Застройщики</option></select></label><label>Название или город <input id="query" maxlength="120"></label><button>Найти</button></form><p id="status" role="status" aria-live="polite"></p><section id="records"></section><button id="next" hidden>Следующая страница</button><section id="detail" aria-live="polite"></section></main></body></html>`;
export const researchClient=String.raw`
const el=id=>document.getElementById(id),root='/mira/api/admin/research';let cursor='',generation=0,currentKind='agency',currentQuery='';
const names={received:'Получено'};
async function api(path,params={}){const r=await fetch(root+path+'?'+new URLSearchParams(params),{credentials:'same-origin',cache:'no-store'});if(!r.headers.get('Content-Type')?.includes('application/json'))throw Error('Войдите в кабинет заново.');const b=await r.json();if(!r.ok)throw Error(r.status===403?'Нужна активная роль оператора.':r.status===401?'Войдите в кабинет заново.':b.error);return b;}
function node(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n;}
const show=v=>v===null?'Не найдено':typeof v==='object'?JSON.stringify(v,null,2):String(v);
async function detail(id,kind){const g=generation;try{const b=await api('/entity',{kind,id});if(g!==generation)return;const box=el('detail');box.replaceChildren();node('h2',b.entity.name,box);node('p','ID: '+id,box);for(const f of b.fields){const card=node('article',undefined,box);node('h3',f.field,card);node('pre',show(f.value),card);node('p','Проверка: '+f.verification_status+' · Контакт: '+f.conversation_scope,card);const d=node('details',undefined,card);node('summary','Источники и даты проверки',d);node('pre',show(f.evidence),d);}if(kind==='developer'){const section=node('section',undefined,box);node('h3','Связи с проектами',section);let linkCursor='';const button=node('button','Показать проекты',section);button.addEventListener('click',async()=>{button.disabled=true;try{const result=await api('/links',{kind,id,cursor:linkCursor});if(g!==generation)return;for(const p of result.records)node('p',p.project_id+' · '+p.mapping_status,section);linkCursor=result.next_cursor;button.hidden=!linkCursor;button.textContent='Ещё проекты';}catch(e){el('status').textContent=e.message;}finally{button.disabled=false;}});}}catch(e){if(g===generation)el('status').textContent=e.message;}}
async function list(next=false){const g=++generation;el('status').textContent='Загрузка…';el('next').disabled=true;el('detail').replaceChildren();if(!next){cursor='';currentKind=el('kind').value;currentQuery=el('query').value.trim();}try{const b=await api('/entities',{kind:currentKind,q:currentQuery,cursor});if(g!==generation)return;const records=el('records');records.replaceChildren();for(const row of b.records){const card=node('article',undefined,records);node('h2',row.name,card);node('p',[row.source_id,row.city,row.market,row.segment].filter(Boolean).join(' · '),card);const button=node('button','Контакты и доказательства',card);button.addEventListener('click',()=>detail(row.source_id,row.kind));}cursor=b.next_cursor;el('next').hidden=!cursor;el('status').textContent=b.records.length?'Записей на странице: '+b.records.length:'Совпадений нет.';}catch(e){if(g===generation)el('status').textContent=e.message;}finally{if(g===generation)el('next').disabled=false;}}
el('search').addEventListener('submit',e=>{e.preventDefault();list();});el('next').addEventListener('click',()=>list(true));
try{const b=await api('');el('summary').textContent='Агентства: '+b.snapshot.agency_candidates+' · Группы застройщиков: '+b.snapshot.developer_groups+' · Связи проектов: '+b.snapshot.research_project_links+' · Источник: '+b.snapshot.source_commit;await list();}catch(e){el('status').textContent=e.message;}
`;
