/** Read-only protected catalogue. No uploads, tokens, sharing or external requests. */
const root=document.querySelector('#library-content'),badge=document.querySelector('#library-status');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={'application/pdf':'pdf','image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
const kindNames={brochure:'Брошюра',floor_plan:'Планировка',field_report:'Локальный отчёт',training:'Обучение'};
const errors={membership_required:'Рабочий доступ ещё не назначен или отозван.',agency_not_active:'Агентство не активировано или приостановлено.',agency_agreement_not_current:'Нужно актуальное подтверждение договора агентства.',material_delivery_closed:'Выдача материалов ещё не открыта.',material_not_available:'Права или срок действия материала изменились. Обновите список.',material_not_found:'Материал не найден в доступном каталоге.',material_object_missing_or_changed:'Файл отсутствует либо отличается от проверенной версии.',material_content_changed:'Версия файла не совпала с проверенной. Выдача остановлена.',project_not_found:'Проект не назначен вашему агентству.',identity_required:'Нужен защищённый вход.',invalid_identity:'Сессия доступа недействительна.'};
let viewVersion=0,currentGroup=null;
async function request(path){
 let r;try{r=await fetch('/mira/api'+path,{credentials:'same-origin',cache:'no-store',redirect:'error'});}catch{throw new Error('Сервер недоступен. Рабочие данные не заменены демонстрационными.');}
 if(!r.ok){let code='';try{code=(await r.json()).error||'';}catch{}throw new Error(errors[code]||`Запрос не выполнен (${r.status}). Войдите через защищённый кабинет или повторите загрузку.`);}
 return r;
}
async function api(path){const r=await request(path);if(!r.headers.get('Content-Type')?.includes('application/json'))throw new Error('Вместо API получена страница сайта. Данные не подтверждены.');return r.json();}
function fail(e){root.innerHTML=`<div class="panel warning"><h2>Рабочий каталог пока недоступен</h2><p>${esc(e.message)}</p><p>Цены, проекты и статусы из демо здесь не подставляются.</p><a class="button secondary" href="./pilot.html">Проверить вход в кабинет</a> <a href="./marketplace.html">Открыть отдельное демо</a></div>`;}
function run(fn){fn().catch(fail);}
async function groups(cursor=''){
 const version=++viewVersion,data=await api('/developers'+(cursor?'?cursor='+encodeURIComponent(cursor):''));if(version!==viewVersion)return;currentGroup=null;
 root.innerHTML=`<div class="library-tools"><label>Поиск по группам на этой странице<input id="family-filter" type="search" placeholder="Название группы"></label></div><p class="muted library-note">Показаны только группы назначенных проектов, а не весь портфель застройщика. Юридический продавец и коммерческий допуск проверяются в карточке конкретного проекта.</p><div id="family-cards" class="cards"></div><p id="family-count" role="status"></p>`;
 const draw=()=>{const q=document.querySelector('#family-filter').value.trim().toLocaleLowerCase('ru'),rows=data.records.filter(x=>(x.name||'Группа не определена').toLocaleLowerCase('ru').includes(q));document.querySelector('#family-cards').innerHTML=rows.map(x=>`<article class="panel"><div class="eyebrow">Группа каталога</div><h2>${esc(x.name||'Группа не определена')}</h2><p>Назначенных проектов: ${esc(x.assigned_project_count)}</p><p class="muted">${esc(x.markets.map(y=>y==='phuket'?'Пхукет':y).join(' · '))}</p><button type="button" data-group="${esc(x.id)}">Открыть проекты</button></article>`).join('')||'<div class="panel">В этой выборке нет назначенных групп.</div>';document.querySelector('#family-count').textContent=`Групп в выборке страницы: ${rows.length}. Это не количество договорных застройщиков.`;root.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>run(()=>group(b.dataset.group)));};document.querySelector('#family-filter').oninput=draw;draw();
 if(data.next_cursor){const b=document.createElement('button');b.textContent='Следующая страница групп';b.onclick=()=>run(()=>groups(data.next_cursor));root.append(b);}
}
async function group(id){
 if(!/^DEV-[a-f0-9]{24}$/.test(id))throw new Error('Некорректный идентификатор группы.');
 const version=++viewVersion,data=await api('/developers/'+id);if(version!==viewVersion)return;currentGroup=id;
 root.innerHTML=`<div class="library-back"><button type="button" id="all-groups">Все назначенные группы</button></div><h2>${esc(data.name||'Группа не определена')}</h2><p class="library-note muted">Это группировка каталога, не юридическое заключение о продавце. Показаны проекты, назначенные вашему агентству; наличие и условия сделки отдельно не подтверждены.</p><div class="cards">${data.projects.map(p=>`<article class="panel"><div class="eyebrow">${esc(p.market==='phuket'?'Пхукет':p.market)}</div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.id)}</p><button type="button" data-project="${esc(p.id)}">Карточка и материалы</button></article>`).join('')}</div>`;
 document.querySelector('#all-groups').onclick=()=>run(()=>groups());root.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>run(()=>project(b.dataset.project)));
}
async function project(id,cursor=''){
 if(!/^[A-Za-z0-9_-]{1,100}$/.test(id))throw new Error('Некорректный идентификатор проекта.');
 const version=++viewVersion,[card,materials]=await Promise.all([api('/projects/'+id),api('/projects/'+id+'/materials'+(cursor?'?cursor='+encodeURIComponent(cursor):''))]);if(version!==viewVersion)return;
 const p=card.project;root.innerHTML=`<div class="library-back"><button type="button" id="back-to-groups">К каталогу застройщиков</button><a class="button secondary" href="./pilot.html">Клиентские запросы в кабинете</a></div><div class="eyebrow">${esc(p.market==='phuket'?'Пхукет':p.market)}</div><h2>${esc(p.name)}</h2><p class="muted">${esc(p.developer_family||'Группа не определена')} · ${esc(p.id)}</p><div class="library-state"><strong>${card.registration_eligible?'Условия допуска проверены API на момент запроса':'Коммерческая регистрация не открыта'}</strong><p>Это не актуальное наличие конкретной единицы и не подтверждение клиента застройщиком. Материалы не заменяют правила сделки.</p></div><h2>Материалы для агентства</h2><p>Только внутреннее использование. Права на пересылку покупателю или публичную рекламу здесь не выдаются.</p><div id="asset-rows"></div>`;
 document.querySelector('#back-to-groups').onclick=()=>run(()=>currentGroup?group(currentGroup):groups());const list=document.querySelector('#asset-rows');
 if(materials.delivery_status==='not_configured_or_closed'){list.innerHTML='<div class="panel warning">Защищённая выдача материалов ещё не настроена или закрыта. Публичные ссылки и файлы из договорного хранилища не подставляются.</div>';return;}
 list.innerHTML=materials.records.map(x=>`<article class="material-row"><div><h3>${esc(x.title)}</h3><p>${esc(kindNames[x.kind]||x.kind)} · ${esc(x.language.toUpperCase())} · ${esc(x.size_bytes)} байт</p><small>Действует до ${esc(x.expires_at)}. Доступ и версия повторно проверяются при скачивании.</small></div><button type="button" data-asset="${esc(x.id)}">Получить файл</button><div class="download-status" role="status"></div></article>`).join('')||'<div class="panel">На этой странице нет материалов с действующими правами. Это не утверждение, что у застройщика нет документов.</div>';
 list.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>download(materials.records.find(x=>x.id===b.dataset.asset),b));
 if(materials.next_cursor){const b=document.createElement('button');b.textContent='Следующая страница материалов';b.onclick=()=>run(()=>project(id,materials.next_cursor));root.append(b);}
}
async function download(meta,button){
 const output=button.parentElement.querySelector('[role=status]');button.disabled=true;output.textContent='Проверяем права и версию файла…';
 try{
  if(!meta||!/^MAT-[A-Za-z0-9_-]+$/.test(meta.id)||!Object.hasOwn(types,meta.mime_type)||!Number.isSafeInteger(meta.size_bytes)||meta.size_bytes<1||meta.size_bytes>8388608||!/^[a-f0-9]{64}$/.test(meta.sha256))throw new Error('Метаданные файла не прошли проверку.');
  const r=await request('/materials/'+meta.id+'/download');if(r.headers.get('Content-Type')!==meta.mime_type||Number(r.headers.get('Content-Length'))!==meta.size_bytes)throw new Error('Ответ сервера не совпал с проверенным файлом.');
  const reader=r.body.getReader(),bytes=new Uint8Array(meta.size_bytes);let pos=0;try{while(true){const part=await reader.read();if(part.done)break;if(pos+part.value.length>bytes.length)throw new Error('Размер файла изменился.');bytes.set(part.value,pos);pos+=part.value.length;}}catch(e){await reader.cancel().catch(()=>{});throw e;}finally{reader.releaseLock();}
  const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');if(pos!==meta.size_bytes||digest!==meta.sha256)throw new Error('Контрольная сумма не совпала. Файл не выдан.');
  const url=URL.createObjectURL(new Blob([bytes],{type:meta.mime_type})),a=document.createElement('a');a.href=url;a.download=meta.id+'.'+types[meta.mime_type];document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);output.textContent='Проверенный файл передан браузеру. Сохранение на устройство не подтверждается; передача клиенту отдельно не разрешена.';
 }catch(e){output.textContent=e.message;}finally{button.disabled=false;}
}
(async()=>{try{const session=await api('/session');if(!session.membership)throw new Error('Активное участие в агентстве ещё не назначено.');badge.textContent='Защищённая сессия';await groups();}catch(e){badge.textContent='Доступ не подтверждён';fail(e);}})();
