import {text,safeURL,filterProjects,createDemoLead,createDemoPayment,protectionLabel,labels} from './core.mjs';
const $=s=>document.querySelector(s), root=$('#content');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={projects:[],leads:[],payments:[]};
const kindName={condo:'Кондоминиум',villa:'Вилла'};
const query=()=>new URLSearchParams(location.search);
function navigate(view,project){const u=new URL(location.href);u.search='';u.searchParams.set('view',view);if(project)u.searchParams.set('project',project);history.pushState({},'',u);render();$('#main').focus();}
function link(view,label,project){return `<a class="button secondary" href="?view=${esc(view)}${project?'&amp;project='+encodeURIComponent(project):''}">${esc(label)}</a>`;}
function download(name,value){const b=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function heading(k,t,p=''){return `<div class="eyebrow">${esc(k)}</div><h1>${esc(t)}</h1>${p?'<p class="muted">'+esc(p)+'</p>':''}`;}
function facts(rows){return '<dl class="facts">'+rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(text(v))}</dd></div>`).join('')+'</dl>';}
function options(values,all){return `<option value="">${esc(all)}</option>`+[...new Set(values)].filter(Boolean).sort().map(v=>`<option value="${esc(v)}">${esc(kindName[v]||v)}</option>`).join('');}
function catalogue(){root.innerHTML=heading('Первый рынок · Пхукет','Проекты для знакомства','Это существующий исследовательский каталог, а не подтверждённый доступный инвентарь.')+`<div class="filters"><label>Поиск<input id="search" type="search" placeholder="Проект, район, группа" autocomplete="off"></label><label>Район<select id="district">${options(state.projects.map(p=>p.district),'Все районы')}</select></label><label>Тип<select id="kind">${options(state.projects.map(p=>p.kind),'Все типы')}</select></label><label class="wide">Группа / бренд девелопера<select id="developer">${options(state.projects.map(p=>p.developerFamily),'Все группы')}</select></label></div><p class="muted">Бюджет, срок сдачи и рассрочка не фильтруются: актуальные подтверждённые значения ещё не загружены.</p><p id="count" role="status"></p><div id="cards" class="cards"></div>`;
 const refresh=()=>{const rows=filterProjects(state.projects,{search:$('#search').value,district:$('#district').value,kind:$('#kind').value,developerFamily:$('#developer').value});$('#count').textContent=`Найдено проектов: ${rows.length}`;$('#cards').innerHTML=rows.length?rows.map(p=>`<article class="card"><span class="badge">Исследовательская карточка</span><h2>${esc(p.name)}</h2><p>${esc(p.district)} · ${esc(kindName[p.kind]||p.kind)}</p><p class="muted">${esc(p.developerFamily)}</p>${link('project','Открыть карточку',p.id)}</article>`).join(''):'<p>Нет проектов с такими фильтрами. Измените запрос.</p>';};
 ['search','district','kind','developer'].forEach(id=>$('#'+id).addEventListener('input',refresh));refresh();}
function project(){const p=state.projects.find(p=>p.id===query().get('project'));if(!p){root.innerHTML=heading('Каталог','Проект не найден')+link('catalog','К каталогу');return;}
 root.innerHTML=link('catalog','← Все проекты')+heading(p.district,p.name)+facts([['Рынок','Таиланд / Пхукет'],['Тип',kindName[p.kind]||p.kind],['Группа / бренд, не юридический продавец',p.developerFamily],['Юридический продавец',null],['Актуальная цена / наличие',null],['Срок сдачи / план оплаты',null],['Комиссия и основание начисления',null],['Регистрация / защита клиента',null],['Источник',p.provenance?.sourceType],['Дата коммерческой проверки',p.provenance?.verifiedAt]])+`<div class="panel warning"><strong>Не является предложением к продаже.</strong><p>Связь с группой взята из внутреннего каталога. Юридический продавец, агентский договор, наличие и правила регистрации требуют отдельного подтверждения. Условие «до 90%» не используется для расчёта комиссии.</p></div><h2>Проверить путь регистрации</h2><form id="lead-form" class="panel"><label>Условный ID клиента<input id="client-ref" value="DEMO-CLIENT-1" pattern="[Dd][Ee][Mm][Oo]-[A-Za-z0-9-]{1,40}" maxlength="45" required></label><p class="muted">Только условный ID. Не вводите имя, телефон, паспорт, банковские реквизиты или контакт клиента.</p><button type="submit">Создать демо-черновик</button><p id="lead-message" role="status"></p></form>`;
 $('#lead-form').addEventListener('submit',e=>{e.preventDefault();const msg=$('#lead-message');try{const l=createDemoLead(p,$('#client-ref').value.trim(),state.leads);state.leads.push(l);navigate('clients');}catch(err){msg.className='error';msg.textContent=err.message;}});}
function clients(){root.innerHTML=heading('Без отправки данных','Клиенты и статусы','Демо-черновики существуют только до перезагрузки этой страницы. Подтверждение застройщика не имитируется.')+(state.leads.length?state.leads.map(l=>`<section class="panel"><span class="badge">${esc(labels[l.status])}</span><h2>${esc(l.clientRef)} · ${esc(l.projectName)}</h2>${facts([['Локальный ID',l.id],['Создан',l.createdAt],['Защита клиента',protectionLabel(l)],['Сделка','Не начата'],['Комиссия','Не начислена; сумма не определена']])}<p>${esc(l.history[0].note)}</p><div class="actions"><button class="secondary" data-export="${esc(l.id)}">Скачать демо-черновик</button><button data-payment="${esc(l.id)}">Демо платёжного запроса</button></div></section>`).join(''):'<div class="panel"><h2>Клиентов пока нет</h2><p>Откройте проект и создайте условный черновик. Это не регистрация у девелопера.</p>'+link('catalog','Выбрать проект')+'</div>')+`<div class="row"><h2>Путь рабочего статуса</h2><p>Получено МИРА → проверка → передано застройщику → подтверждено застройщиком. Возможны уточнение, дубликат и спор.</p><p>Консультация → бронь → договор → платёж → комиссия начислена → получена МИРА → выплачена агентству. Каждому подтверждённому этапу нужен документ; здесь эти события не создаются.</p></div>`;
 root.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>download('mira-demo-lead.json',state.leads.find(l=>l.id===b.dataset.export)));
 root.querySelectorAll('[data-payment]').forEach(b=>b.onclick=()=>{if(!state.payments.some(p=>p.leadId===b.dataset.payment))state.payments.push(createDemoPayment(state.leads.find(l=>l.id===b.dataset.payment)));navigate('payments');});}
function payments(){root.innerHTML=heading('Отдельная услуга','Платёжная поддержка','Демо не принимает деньги и документы. Ни стоимость, ни маршрут, ни исполнение платежа не подтверждены.')+(state.payments.length?state.payments.map(p=>`<section class="panel"><span class="badge">Локальный демо-черновик</span><h2>${esc(state.leads.find(l=>l.id===p.leadId)?.clientRef)}</h2>${facts([['Связанный черновик',p.leadId],['Стоимость / предложение',null],['Статус исполнения','Не передано на исполнение']])}<p>В рабочем процессе оператор отдельно проверяет инвойс, плательщика, получателя, валюты, сумму и доступность допустимого решения. Покупательский платёж и агентская комиссия не смешиваются.</p></section>`).join(''):'<div class="panel"><p>Начните с демо-черновика клиента. Запрос должен быть связан с конкретным проектом и клиентским обращением.</p>'+link('clients','К клиентам')+'</div>');}
function markets(){const groups=[...new Set(state.projects.map(p=>p.developerFamily))].sort();root.innerHTML=heading('Рынки и предложение','Начинаем с Пхукета','Количество строк каталога не означает количество подписанных девелоперов.')+`<div class="panel"><h2>Таиланд / Пхукет</h2><p>Исследовательский каталог доступен в демо. Коммерческий пилот требует подтверждённого проекта, условий и рабочего пути регистрации.</p>${link('catalog','Открыть проекты')}</div><div class="panel"><h2>Бали · Вьетнам · Дубай</h2><p>Следующие направления — сбор спроса и подготовка. Они не обозначаются как действующие рынки.</p></div><h2>Группы из текущего каталога</h2>`+groups.map(g=>`<div class="row"><strong>${esc(g)}</strong><p class="muted">Бренд / группа. Юридический продавец и агентские условия определяются для каждого проекта отдельно.</p></div>`).join('');}
function onboarding(){root.innerHTML=heading('Путь первого клиента','Материалы и обучение')+`<div class="panel"><h2>Стартовый набор Пхукет</h2><p>Проверочный лист проекта, бриф клиента и порядок первого запроса — без неподтверждённых цен и доходности.</p><a class="button" href="./phuket-starter-kit.html">Открыть стартовый набор</a></div><ol><li>Квалификация: контакт руководителя, формат агентства, запрос и ответственный менеджер.</li><li>Согласование договора, доступа и роли агентства. Подписание не считается активацией.</li><li>Оператор включает только проекты с подтверждёнными правилами.</li><li>Агентство готовит реальный клиентский запрос и основание для обработки данных.</li><li>МИРА проверяет запрос, получает ответ застройщика и фиксирует условия защиты.</li><li>Агентство продолжает вести клиента. Сделка и комиссия проходят документированные статусы.</li></ol><h2>Что проверяем перед первой регистрацией</h2><p>Продавец, действующий договор, правила lead registration, срок защиты, дубликаты и споры, актуальный inventory, комиссионный schedule, материалы и ответственный оператор.</p>`;}
function profile(){root.innerHTML=heading('Доступ и роли','Профиль агентства')+facts([['Текущая среда','DEMO'],['Идентификатор','DEMO-AGENCY'],['Доступ','Публичная демонстрация без авторизации'],['Реальные клиенты','Недоступны'],['Подключённые коммерческие проекты','Не подтверждены']])+`<div class="panel warning"><h2>Это не имитация входа</h2><p>Рабочий кабинет включается только после настройки защищённого серверного доступа и проверки прав агентства. Пароль, токен и данные клиента здесь не запрашиваются.</p></div>`+link('application','Подготовить заявку');}
function application(){root.innerHTML=heading('Подключение · подготовка','Заявка агентства','Пока серверный intake не введён в эксплуатацию, эта форма создаёт только локальный бриф. Контакты здесь не собираются.')+`<form id="application-form" class="panel"><div class="form-grid"><label>Формат<select name="format"><option value="agency">Агентство</option><option value="broker">Независимый брокер</option><option value="network">Сеть / франшиза</option></select></label><label>Зарубежное направление<select name="experience"><option value="unknown">Нужно обсудить</option><option value="new">Планируем открыть</option><option value="existing">Уже работаем</option><option value="phuket">Уже продаём Пхукет</option></select></label><label>Клиентский запрос<select name="demand"><option value="learning">Изучаем направление</option><option value="potential">Есть потенциальный интерес</option><option value="current">Есть текущий запрос</option></select></label><label>Приоритет<select name="market"><option>Пхукет</option><option>Бали</option><option>Вьетнам</option><option>Дубай</option></select></label><label class="full"><input type="checkbox" required>Понимаю, что это локальный бриф, не отправленная заявка и не подключение.</label></div><div class="actions"><button type="submit">Скачать локальный бриф</button></div><p id="application-message" role="status"></p></form><p>Рабочая заявка должна получить серверный ID и ответ менеджера. Подготовка файла не означает, что МИРА его получила.</p>`;
 $('#application-form').onsubmit=e=>{e.preventDefault();download('mira-agency-brief.json',{schemaVersion:1,environment:'draft',sent:false,...Object.fromEntries(new FormData(e.target)),createdAt:new Date().toISOString()});$('#application-message').className='success';$('#application-message').textContent='Бриф подготовлен. Не отправлен МИРА. Контактные данные не собирались.';};}
function render(){const view=query().get('view')||'catalog';document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});({catalog:catalogue,project,clients,payments,markets,onboarding,profile,application}[view]||catalogue)();}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const url=new URL(a.href);if(url.origin===location.origin&&url.pathname===location.pathname&&url.searchParams.has('view')){e.preventDefault();navigate(url.searchParams.get('view'),url.searchParams.get('project'));}});
window.addEventListener('popstate',render);$('#reset').onclick=()=>{state.leads=[];state.payments=[];render();};
try{const response=await fetch('./data/catalog.json',{cache:'no-store'});if(!response.ok)throw new Error('Каталог временно недоступен.');const data=await response.json();if(!Array.isArray(data.projects))throw new Error('Некорректный формат каталога.');state.projects=data.projects.map(p=>({...p,provenance:data.provenance}));render();}catch(err){root.innerHTML=heading('Каталог','Не удалось загрузить данные')+`<p class="error">${esc(err.message)}</p><p>Статусы и наличие не подставляются из примера. Перезагрузите страницу позже.</p>`;}
