/** Protected pilot UI. Same-origin Access session; no browser token storage. */
const root=document.querySelector('#pilot-content');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={received:'Получено МИРА',submitted:'Получено МИРА',review:'Проверка МИРА',needs_information:'Нужно уточнение',developer_submitted:'Передано застройщику',developer_confirmed:'Подтверждено застройщиком',duplicate:'Дубликат',conflict:'Спор',rejected:'Отклонено',expired:'Срок истёк',closed:'Закрыто',package_review:'Проверка платёжного запроса'};
let session=null,section='application',applicationAttempt=null;
const errors={identity_required:'Нужен вход через защищённый доступ.',invalid_identity:'Сессия недействительна. Повторите вход.',membership_required:'Оператор ещё не назначил доступ агентству.',agency_not_active:'Доступ агентства ещё не активирован или приостановлен.',agency_agreement_not_current:'Нужно подтверждение актуального агентского договора.',project_not_enabled:'Проект не включён для регистрации.',evidence_missing_stale_or_wrong_scope:'Подтверждение отсутствует, устарело или относится к другому клиенту/проекту.',duplicate_registration_in_agency:'Такой внутренний ID уже зарегистрирован по этому проекту в агентстве. Проверьте список клиентов.',stale_version:'Статус уже изменился. Обновите карточку.',applications_not_enabled:'Серверный приём заявок ещё не включён.',application_rate_limit:'Достигнут лимит заявок. Повтор не создавайте; проверьте уже полученные заявки.',origin_rejected:'Запрос отклонён проверкой источника.',project_access_required:'Агентству не назначен доступ к этому проекту.',operator_required:'Раздел доступен только оператору.'};
async function api(path,body,headers={}){
 const response=await fetch('/mira/api'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',redirect:'error',headers:body===undefined?{}:{'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});
 if(!response.headers.get('Content-Type')?.includes('application/json'))throw new Error('Рабочий API недоступен: получен ответ сайта вместо серверного подтверждения.');
 const data=await response.json();if(!response.ok)throw new Error(errors[data.error]||`Запрос не принят (${response.status}; ${data.error||'ошибка сервера'}).`);return data;
}
function title(t,note=''){return `<div class="eyebrow">МИРА · закрытый пилот</div><h1>${esc(t)}</h1><p class="muted">${esc(note)}</p>`;}
function message(text){root.innerHTML=title('Доступ пока недоступен')+`<div class="panel warning"><p>${esc(text)}</p><p>Заявка не отправлена. Статусы и данные не подставлены из демо. Рабочий вход включается после настройки сервера и политики доступа.</p><a class="button" href="./marketplace.html">Открыть отдельное демо</a></div>`;}
async function withForm(form,action){const output=form.querySelector('[role=status]'),button=form.querySelector('button[type=submit]');button.disabled=true;output.className='';try{await action(output);}catch(e){output.className='error';output.textContent=e.message;}finally{button.disabled=false;}}
function privacyLink(){try{const u=new URL(session.privacy_notice_url);return u.origin===location.origin?u.href:null;}catch{return null;}}
async function application(){
 const notice=privacyLink();root.innerHTML=title('Подключить агентство','Серверный номер означает получение заявки МИРА, а не одобрение, договор или активацию.')+`<p>Авторизованный контакт: <strong>${esc(session.email)}</strong></p>`;
 if(!session.applications_enabled||!session.privacy_version||!notice){root.innerHTML+='<div class="panel warning">Приём заявок ещё не включён: оператор должен завершить настройки и опубликовать согласованную информацию об обработке данных.</div>';return;}
 root.innerHTML+=`<form id="application" class="panel"><div class="form-grid"><label>Агентство<input name="company" required maxlength="120" autocomplete="organization"></label><label>Город<input name="city" required maxlength="120" autocomplete="address-level2"></label><label>Имя представителя<input name="name" required maxlength="120" autocomplete="name"></label><label>Формат<select name="format"><option value="agency">Агентство</option><option value="broker">Независимый брокер</option><option value="network">Сеть</option></select></label><label>Текущий запрос<select name="demand"><option value="learning">Изучаем направление</option><option value="potential">Есть потенциальный интерес</option><option value="current">Есть клиентский запрос</option></select></label><label>Направление<select name="market"><option value="phuket">Пхукет</option><option value="bali">Бали — подготовка</option><option value="vietnam">Вьетнам — подготовка</option><option value="dubai">Дубай — подготовка</option></select></label><label class="full"><input type="checkbox" required>Ознакомился с <a href="${esc(notice)}" target="_blank" rel="noopener noreferrer">информацией об обработке данных</a> и соглашаюсь с указанными условиями подачи заявки.</label></div><p class="muted">Не вводите здесь сведения о покупателе, паспорта или банковские данные.</p><button type="submit">Отправить заявку МИРА</button><p role="status"></p></form><h2>Мои заявки</h2><div id="applications-list"></div>`;
 const load=async()=>{const data=await api('/applications');document.querySelector('#applications-list').innerHTML=data.records.map(x=>`<div class="row"><strong>${esc(x.company)}</strong><p>${esc(names[x.status]||x.status)} · ${esc(x.created_at)}</p><code>${esc(x.id)}</code></div>`).join('')||'<p>Полученных заявок нет.</p>';};
 document.querySelector('#application').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{
   const f=Object.fromEntries(new FormData(e.target)),body={company:f.company,city:f.city,name:f.name,format:f.format,demand:f.demand,markets:[f.market],consent_version:session.privacy_version},serialized=JSON.stringify(body);
   if(applicationAttempt?.serialized!==serialized)applicationAttempt={serialized,key:crypto.randomUUID()};
   const receipt=await api('/applications',body,{'Idempotency-Key':applicationAttempt.key});output.className='success';output.textContent=`Получено МИРА. Номер ${receipt.id}. Дата ${receipt.received_at}. Подключение ещё не подтверждено.`;await load();
 });};await load();
}
async function projects(){
 const data=await api('/projects');root.innerHTML=title('Проекты','В рабочем списке находятся только проекты, назначенные вашему агентству. Перед каждым запросом сервер заново проверяет актуальность подтверждений.')+`<div class="cards">${data.records.map(p=>`<article class="card"><span class="badge">${p.enabled?'Включён · актуальность проверяется при отправке':'Не включён для регистрации'}</span><h2>${esc(p.name)}</h2><p>${esc(p.developer_family||'Группа не определена')}</p><p>Продавец: ${esc(p.legal_seller||'Не подтверждён')}</p><code>${esc(p.id)}</code></article>`).join('')||'<p>Проекты пока не назначены. Оператор должен подтвердить доступ и условия.</p>'}</div>`;
 if(session.membership?.role==='operator')return;
 root.innerHTML+=`<h2>Запрос регистрации клиента</h2><form id="registration" class="panel"><div class="form-grid"><label>Проект<select name="project_id" required>${data.records.filter(p=>p.enabled).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><label>Внутренний ID из вашей CRM<input name="client_ref" pattern="[A-Za-z0-9_-]+" required maxlength="100" placeholder="Только внутренний ID"></label><label class="full">ID подтверждения согласия, полученный от оператора<input name="consent_ref" pattern="EVID-[A-Za-z0-9_-]+" required maxlength="100" placeholder="EVID-…"></label></div><p class="muted">Не вводите ФИО, телефон или документы клиента. Если оператор ещё не зафиксировал основание для обработки и передачи данных, запрос не будет принят.</p><button type="submit">Передать на проверку МИРА</button><p role="status"></p></form>`;
 document.querySelector('#registration').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{const r=await api('/leads',Object.fromEntries(new FormData(e.target)));output.className='success';output.textContent=`Получено МИРА: ${r.id}. Подтверждения застройщика и защиты клиента пока нет.`;});};
}
async function leads(cursor=''){
 const data=await api('/leads'+(cursor?'?cursor='+encodeURIComponent(cursor):''));root.innerHTML=title('Клиенты','Заявка, регистрация застройщика, сделка и комиссия показываются отдельно.')+data.records.map(l=>`<article class="panel"><span class="badge">${esc(names[l.status]||l.status)}</span><h2>${esc(l.client_ref)}</h2><p>Проект: ${esc(l.project_id)}</p><p>Поступил: ${esc(l.created_at)}</p><button type="button" data-lead="${esc(l.id)}">Открыть статусы</button></article>`).join('');
 if(!data.records.length)root.innerHTML+='<div class="panel">Рабочих клиентских запросов нет.</div>';
 root.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>detail(b.dataset.lead).catch(e=>message(e.message)));
 if(data.next_cursor){const b=document.createElement('button');b.textContent='Следующая страница';b.onclick=()=>leads(data.next_cursor).catch(e=>message(e.message));root.append(b);}
}
async function detail(id){
 const data=await api('/leads/'+encodeURIComponent(id)),l=data.lead;
 root.innerHTML=title(l.client_ref,l.project_id)+`<span class="badge">${esc(names[l.status]||l.status)}</span><p>Защита: ${data.protection_status==='recorded_confirmation'?'Есть актуальная запись подтверждения до '+esc(l.protection_until):'Не подтверждена / не актуальна'}</p><h2>Журнал</h2>${data.events.map(e=>`<div class="row"><strong>${esc(names[e.status]||e.status)}</strong><p>${esc(e.reason)}</p><small>${esc(e.created_at)}</small></div>`).join('')}<h2>Сделка и комиссия</h2>${data.deal.length?data.deal.map(e=>`<div class="row"><strong>${esc(e.stage)}</strong><p>${e.amount_decimal?esc(e.amount_decimal)+' '+esc(e.currency):'Сумма не относится к этому этапу'}</p><small>${esc(e.created_at)}</small></div>`).join(''):'<p>Подтверждённых событий сделки/комиссии ещё нет.</p>'}<h2>Платёжная поддержка</h2>`;
 if(data.payment)root.innerHTML+=`<div class="panel">${esc(names[data.payment.status]||data.payment.status)} · ${esc(data.payment.invoice_currency)}<p>Запрос не равен исполнению платежа. Цена и исполнение здесь не подтверждаются.</p></div>`;
 else if(session.membership?.role!=='operator'){
 root.innerHTML+=`<form id="payment" class="panel"><label>Валюта инвойса — трёхбуквенный код<input name="invoice_currency" pattern="[A-Z]{3}" required maxlength="3" placeholder="Из инвойса"></label><label>Ссылка оператора на согласие по платёжному запросу<input name="consent_ref" pattern="EVID-[A-Za-z0-9_-]+" required maxlength="100"></label><p>Не загружайте сюда инвойс или реквизиты. Документы проходят отдельный защищённый процесс.</p><button type="submit">Запросить проверку</button><p role="status"></p></form>`;
 document.querySelector('#payment').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{const r=await api('/payment-requests',{lead_id:id,...Object.fromEntries(new FormData(e.target))});output.className='success';output.textContent=`Запрос ${r.id} получен на проверку. Платёж не исполнялся.`;});};
 }
 if(session.membership?.role==='operator')operatorStatus(id,l);
}
function operatorStatus(id,lead){
 root.innerHTML+=`<h2>Ручная смена статуса</h2><form id="status" class="panel"><label>Следующий статус<select name="status">${['review','needs_information','developer_submitted','developer_confirmed','duplicate','conflict','rejected','expired','closed'].map(s=>`<option value="${s}">${esc(names[s])}</option>`).join('')}</select></label><label>Основание без персональных данных<input name="reason" required minlength="3" maxlength="240"></label><label>Подтверждение события<input name="evidence_ref" pattern="EVID-[A-Za-z0-9_-]+" maxlength="100"></label><label>Owner approval для уже выполненной передачи застройщику<input name="owner_approval_ref" pattern="EVID-[A-Za-z0-9_-]+" maxlength="100"></label><p class="muted">Форма записывает доказанное событие. Она не отправляет сообщение застройщику. Защита клиента в этой форме не назначается автоматически.</p><button type="submit">Записать переход</button><p role="status"></p></form>`;
 document.querySelector('#status').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{const fields=Object.fromEntries([...new FormData(e.target)].filter(([,v])=>v));const r=await api('/admin/leads/'+encodeURIComponent(id)+'/status',{...fields,version:lead.version});lead.version=r.version;output.className='success';output.textContent=`Статус записан: ${names[r.status]||r.status}. Версия ${r.version}.`;});};
}
async function operator(){
 if(session.membership?.role!=='operator')throw new Error('Раздел доступен только оператору.');
 const dashboard=await api('/admin/dashboard'),apps=await api('/admin/applications');root.innerHTML=title('Операционный контроль','Счётчики относятся только к подключённой базе. Они не смешиваются с исследовательским launch dashboard.')+`<div class="panel"><pre>${esc(JSON.stringify(dashboard,null,2))}</pre></div><h2>Входящие заявки</h2>${apps.records.map(a=>`<div class="row"><strong>${esc(a.company)} · ${esc(a.city)}</strong><p>${esc(a.name)} · ${esc(a.email)}</p><p>${esc(a.demand)} · ${esc(a.status)}</p><code>${esc(a.id)}</code></div>`).join('')||'<p>Полученных заявок нет.</p>'}`;
 if(apps.next_cursor)root.innerHTML+='<p class="muted">Показана первая страница. Полная очередь доступна оператору через API с next_cursor.</p>';
}
async function render(){if(!session)return;root.textContent='Загрузка…';try{await ({application,projects,leads,operator}[section]||application)();}catch(e){message(e.message);}}
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;render();});
try{session=await api('/session');await render();}catch(e){message(e.message);}
