/** Protected pilot UI. Same-origin Access session; no browser token storage. */
const root=document.querySelector('#pilot-content');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={received:'Получено МИРА',submitted:'Получено МИРА',review:'Проверка МИРА',needs_information:'Нужно уточнение',developer_submitted:'Передано застройщику',developer_confirmed:'Подтверждено застройщиком',duplicate:'Дубликат',conflict:'Спор',rejected:'Отклонено',expired:'Срок истёк',closed:'Закрыто',package_review:'Проверка платёжного запроса',qualified:'Квалификация подтверждена',onboarded:'Onboarding завершён',booking:'Бронь',contract:'Договор',buyer_payment:'Платёж покупателя',commission_accrued:'Комиссия начислена',commission_received:'Комиссия получена МИРА',agency_paid:'Расчёт с агентством',phuket:'Пхукет'};
let session=null,section='application',applicationAttempt=null;
const leadAttempts=new Map();
const errors={identity_required:'Нужен вход через защищённый доступ.',invalid_identity:'Сессия недействительна. Повторите вход.',membership_required:'Оператор ещё не назначил доступ агентству.',agency_not_active:'Доступ агентства ещё не активирован или приостановлен.',agency_agreement_not_current:'Нужно подтверждение актуального агентского договора.',project_not_enabled:'Проект не включён для регистрации.',evidence_missing_stale_or_wrong_scope:'Подтверждение отсутствует, устарело или относится к другому клиенту/проекту.',duplicate_registration_in_agency:'Такой внутренний ID уже зарегистрирован по этому проекту в агентстве. Проверьте список клиентов.',stale_version:'Статус уже изменился. Обновите карточку.',applications_not_enabled:'Серверный приём заявок ещё не включён.',application_rate_limit:'Достигнут лимит заявок. Повтор не создавайте; проверьте уже полученные заявки.',origin_rejected:'Запрос отклонён проверкой источника.',project_access_required:'Агентству не назначен доступ к этому проекту.',operator_required:'Раздел доступен только оператору.',onboarding_account_not_ready:'Нужны активное агентство, действующий договор и подтверждённая привязка представителя как владельца.',invalid_transition:'Такой переход из текущего состояния не разрешён.',idempotency_payload_mismatch:'Этот номер попытки уже использован для другого запроса. Проверьте сохранённую квитанцию.',payment_request_payload_mismatch:'Платёжный запрос уже существует с другими полями. Откройте карточку и обратитесь к оператору.'};
async function api(path,body,headers={}){
 let response;try{response=await fetch('/mira/api'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',redirect:'error',headers:body===undefined?{}:{'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});}catch{throw new Error(body===undefined?'Сервер временно недоступен. Повторите загрузку.':'Ответ сервера не получен. Запрос мог сохраниться. Повторите его без изменения полей или проверьте список — повтор использует ту же попытку.');}
 if(!response.headers.get('Content-Type')?.includes('application/json'))throw new Error('Рабочий API недоступен: получен ответ сайта вместо серверного подтверждения.');
 const data=await response.json();if(!response.ok&&response.status>=500&&body!==undefined)throw new Error('Сервер не подтвердил результат записи. Запрос мог сохраниться; повторите его без изменения полей или проверьте квитанцию.');if(!response.ok)throw new Error(errors[data.error]||`Запрос не принят (${response.status}; ${data.error||'ошибка сервера'}).`);return data;
}
function title(t,note=''){return `<div class="eyebrow">МИРА · закрытый пилот</div><h1>${esc(t)}</h1><p class="muted">${esc(note)}</p>`;}
function message(text){root.innerHTML=title('Доступ пока недоступен')+`<div class="panel warning"><p>${esc(text)}</p><p>Рабочий API не подтвердил доступ или текущий статус. При сбое после отправки сначала проверьте полученные заявки. Статусы не подставлены из демо.</p><a class="button" href="./marketplace.html">Открыть отдельное демо</a></div>`;}
async function withForm(form,action){const output=form.querySelector('[role=status]'),button=form.querySelector('button[type=submit]');button.disabled=true;output.className='';try{await action(output);}catch(e){output.className='error';output.textContent=e.message;}finally{button.disabled=false;}}
function privacyLink(){try{const u=new URL(session.privacy_notice_url);return u.origin===location.origin?u.href:null;}catch{return null;}}
async function application(){
 const notice=privacyLink();root.innerHTML=title('Начнём с знакомства','Расскажи об агентстве и своём интересе. МИРА рассмотрит заявку, а статус появится здесь.')+`<p class="signed-contact"><span aria-hidden="true">✓</span> Вход подтверждён · <strong>${esc(session.email)}</strong></p>`;
 if(!session.applications_enabled||!session.privacy_version||!notice){root.innerHTML+='<div class="panel warning">Новые заявки сейчас не принимаются. Сохранённые квитанции остаются доступны.</div><h2>Мои заявки</h2><div id="applications-list"></div>';try{const d=await api('/applications');const list=document.querySelector('#applications-list');list.innerHTML=d.records.map(a=>`<div class="row"><strong>${esc(a.company)}</strong><p>${esc(names[a.status]||a.status)}</p><button type="button" data-application="${esc(a.id)}">Открыть заявку</button></div>`).join('')||'<p>Полученных заявок нет.</p>';list.querySelectorAll('[data-application]').forEach(b=>b.onclick=()=>applicationCard(b.dataset.application,false).catch(e=>message(e.message)));}catch(e){document.querySelector('#applications-list').textContent=e.message;}return;}
 root.innerHTML+=`<form id="application" class="panel application-wizard" novalidate>
 <ol class="journey" aria-label="Три шага заявки">${['Об агентстве','Твой интерес','Проверка'].map((label,i)=>`<li><span class="step-number">${i+1}</span><span>${label}</span></li>`).join('')}</ol>
 <fieldset data-step="0"><legend tabindex="-1">1. Об агентстве</legend><p class="muted">Три коротких поля — чтобы мы знали, с кем общаемся.</p><div class="form-grid"><label>Агентство<input name="company" required maxlength="120" autocomplete="organization" placeholder="Название агентства" aria-describedby="company-tip"></label><label>Город<input name="city" required maxlength="120" autocomplete="address-level2" placeholder="Где ты работаешь"></label><label class="full">Твоё имя<input name="name" required maxlength="120" autocomplete="name" placeholder="Как к тебе обращаться"></label></div><details class="inline-help" id="company-tip"><summary>Я работаю самостоятельно</summary><p>Можно указать «Независимый брокер» и своё профессиональное имя. На следующем шаге выбери подходящий формат.</p></details></fieldset>
 <fieldset data-step="1" hidden><legend tabindex="-1">2. Твой интерес</legend><p class="muted">Выбери ближайшую задачу. Это не обязательство заключать сделку.</p><div class="form-grid"><label>Формат<select name="format"><option value="agency">Агентство</option><option value="broker">Независимый брокер</option><option value="network">Сеть</option></select></label><label>Текущий запрос<select name="demand"><option value="learning">Изучаем направление</option><option value="potential">Есть потенциальный интерес</option><option value="current">Есть клиентский запрос</option></select></label><label class="full">Направление<select name="market"><option value="phuket">Пхукет</option><option value="bali">Бали</option><option value="dubai">Дубай</option><option value="vietnam">Вьетнам — интерес к направлению</option></select></label></div><details class="inline-help"><summary>Если уже есть покупатель</summary><p>Сейчас достаточно выбрать «Есть клиентский запрос». Имя, контакты, документы и платёжные данные покупателя сюда не вводи. Доступ к работе с клиентами оформляется отдельно.</p></details></fieldset>
 <fieldset data-step="2" hidden><legend tabindex="-1">3. Проверь и отправь</legend><dl class="application-summary" id="application-summary"></dl><label class="consent"><input name="consent" type="checkbox" required>Я ознакомился с <a href="${esc(notice)}" target="_blank" rel="noopener noreferrer">уведомлением об обработке данных</a> и согласен на обработку указанных данных для рассмотрения заявки, включая описанную инфраструктуру. Это не согласие на рекламу.</label><p class="muted consent-version">Версия уведомления: ${esc(session.privacy_version)}</p><details class="inline-help"><summary>Что будет после отправки?</summary><p>Ты получишь номер заявки. МИРА рассмотрит её, при необходимости запросит уточнения и отразит решение в кабинете. Договор и доступ оформляются отдельно.</p></details></fieldset>
 <div class="actions wizard-actions"><button type="button" id="application-back" class="secondary" hidden>Назад</button><button type="button" id="application-next">Продолжить <span aria-hidden="true">→</span></button><button type="submit" hidden>Отправить заявку МИРА</button></div><p role="status" tabindex="-1"></p></form><h2>Мои заявки</h2><div id="applications-list"></div>`;
 const load=async()=>{const data=await api('/applications'),list=document.querySelector('#applications-list');if(!list)return;list.innerHTML=data.records.map(x=>`<div class="row"><strong>${esc(x.company)}</strong><p>${esc(names[x.status]||x.status)} · ${esc(x.created_at)}</p><code>${esc(x.id)}</code><p><button type="button" data-application="${esc(x.id)}">Открыть заявку</button></p></div>`).join('')||'<p>Полученных заявок нет.</p>';list.querySelectorAll('[data-application]').forEach(b=>b.onclick=()=>applicationCard(b.dataset.application,false).catch(e=>message(e.message)));};
 const form=document.querySelector('#application'),steps=[...form.querySelectorAll('[data-step]')],next=form.querySelector('#application-next'),back=form.querySelector('#application-back'),submit=form.querySelector('[type=submit]');let step=0,received=false;
 const validate=index=>{for(const input of steps[index].querySelectorAll('input,select')){if(!input.checkValidity()||(input.type==='text'&&!input.value.trim())){show(index);input.setCustomValidity(input.type==='text'&&!input.value.trim()?'Заполни это поле.':'');input.reportValidity();input.oninput=()=>input.setCustomValidity('');return false;}}return true;};
 const show=(index,focus=true)=>{step=index;steps.forEach((el,i)=>el.hidden=i!==step);form.querySelectorAll('.journey li').forEach((el,i)=>{el.setAttribute('aria-current',i===step?'step':'false');el.classList.toggle('complete',i<step);});back.hidden=step===0;next.hidden=step===2;submit.hidden=step!==2;form.querySelector('[role=status]').textContent='';if(step===2){const f=form.elements;form.querySelector('#application-summary').innerHTML=[['Агентство',f.company.value],['Город',f.city.value],['Представитель',f.name.value],['Email',session.email],['Формат',f.format.selectedOptions[0].text],['Интерес',f.demand.selectedOptions[0].text],['Направление',f.market.selectedOptions[0].text]].map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('');}if(focus)steps[step].querySelector('legend').focus();};
 next.onclick=()=>{if(validate(step))show(step+1);};back.onclick=()=>show(step-1);show(0,false);
 form.onsubmit=e=>{e.preventDefault();if(received)return;if(step<2){next.click();return;}if(!steps.every((_,i)=>validate(i)))return;withForm(e.target,async output=>{
   const f=Object.fromEntries(new FormData(e.target)),body={company:f.company,city:f.city,name:f.name,format:f.format,demand:f.demand,markets:[f.market],consent_version:session.privacy_version},serialized=JSON.stringify(body);
   if(applicationAttempt?.serialized!==serialized)applicationAttempt={serialized,key:crypto.randomUUID()};
   const receipt=await api('/applications',body,{'Idempotency-Key':applicationAttempt.key});received=true;output.className='success receipt';output.textContent=`Получено МИРА. Номер ${receipt.id}. Дата ${receipt.received_at}. Заявка на рассмотрении. Подключение ещё не подтверждено.`;steps.forEach(el=>el.hidden=true);form.querySelector('.wizard-actions').hidden=true;form.querySelectorAll('.journey li').forEach(el=>el.classList.add('complete'));output.focus();try{await load();}catch{output.textContent+=' Квитанция сохранена; список временно не обновился.';}
 });};try{await load();}catch(e){document.querySelector('#applications-list').textContent=e.message;}
}
async function projects(){
 const data=await api('/projects');root.innerHTML=title('Проекты','Только назначенный вашему агентству каталог. Наличие, цена и договорная комиссия не выводятся без отдельного подтверждения.')+
 `<div class="filters"><label>Название проекта<input id="project-search" type="search" autocomplete="off"></label><label>Рынок<select id="project-market"><option value="">Все доступные</option>${[...new Set(data.records.map(p=>p.market))].map(x=>`<option value="${esc(x)}">${esc(names[x]||x)}</option>`).join('')}</select></label><label>Группа застройщика<select id="project-family"><option value="">Все группы</option>${[...new Set(data.records.map(p=>p.developer_family).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><p id="project-count" role="status"></p><div id="project-cards" class="cards"></div>`;
 const draw=()=>{
  const q=document.querySelector('#project-search').value.trim().toLocaleLowerCase('ru'),market=document.querySelector('#project-market').value,family=document.querySelector('#project-family').value;
  const rows=data.records.filter(p=>(!q||p.name.toLocaleLowerCase('ru').includes(q))&&(!market||p.market===market)&&(!family||p.developer_family===family));
  document.querySelector('#project-count').textContent=`В выборке: ${rows.length}. Это проекты, а не доступные единицы.`;
  document.querySelector('#project-cards').innerHTML=rows.map(p=>`<article class="card"><span class="badge">${p.enabled?'Статус требует проверки в карточке':'Регистрация выключена'}</span><h2>${esc(p.name)}</h2><p>${esc(p.developer_family||'Группа не определена')}</p><button type="button" data-project="${esc(p.id)}">Открыть проект</button></article>`).join('')||'<p>Проекты не найдены или ещё не назначены.</p>';
  root.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>projectCard(b.dataset.project).catch(e=>message(e.message)));
 };
 ['#project-search','#project-market','#project-family'].forEach(s=>document.querySelector(s).addEventListener('input',draw));draw();
}
async function projectCard(id){
 const d=await api('/projects/'+encodeURIComponent(id)),p=d.project;
 const labels={project_agreement:'Договор по проекту и продавец',inventory:'Актуальное наличие',registration_rules:'Правила регистрации',commission_schedule:'Комиссионные условия',materials_rights:'Права на материалы'};
 const states={current:'Актуальное подтверждение',missing:'Нет подтверждения',not_current:'Нужна повторная проверка',expiry_missing:'Не указан срок актуальности',seller_mismatch:'Продавец не совпадает с договором'};
 root.innerHTML=title(p.name,names[p.market]||p.market)+`<div class="actions"><button type="button" id="back-projects" class="secondary">Все проекты</button></div><dl class="facts"><div><dt>Группа / бренд</dt><dd>${esc(p.developer_family||'Не определена')}</dd></div><div><dt>Продавец в записи</dt><dd>${esc(p.legal_seller||'Не подтверждён')}</dd></div><div><dt>Обновление метаданных</dt><dd>${esc(p.updated_at)}</dd></div><div><dt>Регистрация клиента</dt><dd>${d.registration_eligible?'Условия входа проверены; требуется согласие клиента':'Пока недоступна'}</dd></div></dl><h2>Проверка источников</h2>${d.checks.map(c=>`<div class="row"><strong>${esc(labels[c.kind]||c.kind)}</strong><p>${esc(states[c.state]||c.state)}</p><small>Проверено: ${esc(c.verified_at||'Не указано')} · Действует до: ${esc(c.expires_at||'Не указано')}</small></div>`).join('')}<div class="panel warning">Текущая проверка не означает бронирование, подтверждение застройщика или защиту лида. Суммы и доступность конкретной единицы подтверждаются отдельно. Файлы и коммерческие условия выдаёт оператор по защищённому каналу.</div>`;
 document.querySelector('#back-projects').onclick=()=>projects().catch(e=>message(e.message));
 if(!d.registration_eligible||session.membership?.role==='operator')return;
 root.innerHTML+=`<h2>Запрос регистрации клиента</h2><form id="registration" class="panel"><input type="hidden" name="project_id" value="${esc(p.id)}"><div class="form-grid"><label>Внутренний ID из вашей CRM<input name="client_ref" pattern="[A-Za-z0-9_-]+" required maxlength="100" placeholder="Только внутренний ID"></label><label>Подтверждение согласия от оператора<input name="consent_ref" pattern="EVID-[A-Za-z0-9_-]+" required maxlength="100" placeholder="EVID-…"></label></div><p class="muted">Без имени, телефона или документов покупателя. Основание обработки и минимальный пакет проверяет оператор.</p><button type="submit">Передать на проверку МИРА</button><p role="status"></p></form>`;
 // innerHTML insertion recreates the back button; rebind it.
 document.querySelector('#back-projects').onclick=()=>projects().catch(e=>message(e.message));
 document.querySelector('#registration').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{
  const body=Object.fromEntries(new FormData(e.target)),serialized=JSON.stringify(body);
  if(!leadAttempts.has(serialized))leadAttempts.set(serialized,crypto.randomUUID());
  const r=await api('/leads',body,{'Idempotency-Key':leadAttempts.get(serialized)});output.className='success';output.textContent=`Квитанция МИРА: ${r.id}. ${r.replayed?'Показана уже сохранённая заявка.':'Заявка получена.'} Актуальный статус застройщика и защиты смотрите в разделе «Клиенты».`;
 });};
}
async function profile(){
 const p=await api('/profile');root.innerHTML=title('Профиль агентства','Доступ к кабинету сам по себе не считается активацией агентства.')+
 (p.agency?`<dl class="facts"><div><dt>Агентство</dt><dd>${esc(p.agency.name)}</dd></div><div><dt>Город</dt><dd>${esc(p.agency.city)}</dd></div><div><dt>Роль</dt><dd>${p.role==='agency_owner'?'Владелец / руководитель':'Брокер'}</dd></div><div><dt>Договор</dt><dd>${p.agreement_current?'Актуальное подтверждение':'Нужна проверка'}</dd></div><div><dt>Назначенные рынки</dt><dd>${p.available_markets.map(x=>esc(names[x]||x)).join(', ')||'Пока нет'}</dd></div><div><dt>Внутренний ID</dt><dd>${esc(p.agency.id)}</dd></div></dl>`:'<div class="panel">Вы вошли как оператор, а не как агентство.</div>')+
 '<h2>Начало работы</h2><div class="panel"><p>Откройте проект и проверьте его условия входа. Сохраните клиента в своей CRM. Запросите у оператора подтверждение основания для обработки данных. Подайте внутренний ID и сохраните квитанцию. Ждите отдельного подтверждения застройщика.</p><p>Договор, доступ, подтверждение застройщика и защита клиента — разные этапы. Клиент и коммуникация остаются у агентства.</p><a href="./phuket-starter-kit.html" target="_blank" rel="noopener">Стартовый комплект: процесс, а не текущий прайс-лист</a></div>';
}
async function leads(cursor=''){
 const data=await api('/leads'+(cursor?'?cursor='+encodeURIComponent(cursor):''));root.innerHTML=title('Клиенты','Заявка, регистрация застройщика, сделка и комиссия показываются отдельно.')+data.records.map(l=>`<article class="panel"><span class="badge">${esc(names[l.status]||l.status)}</span><h2>${esc(l.client_ref)}</h2><p>Проект: ${esc(l.project_id)}</p><p>Поступил: ${esc(l.created_at)}</p><button type="button" data-lead="${esc(l.id)}">Открыть статусы</button></article>`).join('');
 if(!data.records.length)root.innerHTML+='<div class="panel">Рабочих клиентских запросов нет.</div>';
 root.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>detail(b.dataset.lead).catch(e=>message(e.message)));
 if(data.next_cursor){const b=document.createElement('button');b.textContent='Следующая страница';b.onclick=()=>leads(data.next_cursor).catch(e=>message(e.message));root.append(b);}
}
async function detail(id){
 const data=await api('/leads/'+encodeURIComponent(id)),l=data.lead;
 root.innerHTML=title(l.client_ref,l.project_id)+`<span class="badge">${esc(names[l.status]||l.status)}</span><p>Защита: ${data.protection_status==='recorded_confirmation'?'Есть актуальная запись подтверждения до '+esc(l.protection_until):'Не подтверждена / не актуальна'}</p><h2>Журнал</h2>${data.events.map(e=>`<div class="row"><strong>${esc(names[e.status]||e.status)}</strong><p>${esc(e.reason)}</p><small>${esc(e.created_at)}</small></div>`).join('')}<h2>Сделка и комиссия</h2>${data.deal.length?data.deal.map(e=>`<div class="row"><strong>${esc(names[e.stage]||e.stage)}</strong><p>${e.amount_decimal?esc(e.amount_decimal)+' '+esc(e.currency):'Сумма не относится к этому этапу'}</p><small>${esc(e.created_at)}</small></div>`).join(''):'<p>Подтверждённых событий сделки/комиссии ещё нет.</p>'}<h2>Платёжная поддержка</h2>`;
 if(data.payment)root.innerHTML+=`<div class="panel">${esc(names[data.payment.status]||data.payment.status)} · ${esc(data.payment.invoice_currency)}<p>Запрос не равен исполнению платежа. Цена и исполнение здесь не подтверждаются.</p></div>`;
 else if(session.membership?.role!=='operator'){
 root.innerHTML+=`<form id="payment" class="panel"><label>Валюта инвойса — трёхбуквенный код<input name="invoice_currency" pattern="[A-Z]{3}" required maxlength="3" placeholder="Из инвойса"></label><label>Ссылка оператора на согласие по платёжному запросу<input name="consent_ref" pattern="EVID-[A-Za-z0-9_-]+" required maxlength="100"></label><p>Не загружайте сюда инвойс или реквизиты. Документы проходят отдельный защищённый процесс.</p><button type="submit">Запросить проверку</button><p role="status"></p></form>`;
 document.querySelector('#payment').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{const r=await api('/payment-requests',{lead_id:id,...Object.fromEntries(new FormData(e.target))});output.className='success';output.textContent=`Запрос ${r.id} получен на проверку. Платёж не исполнялся.`;});};
 }
 if(session.membership?.role==='operator')operatorStatus(id,l);
}
function operatorStatus(id,lead){
 root.innerHTML+=`<h2>Ручная смена статуса</h2><form id="status" class="panel"><label>Следующий статус<select name="status">${['review','needs_information','developer_submitted','developer_confirmed','duplicate','conflict','rejected','expired','closed'].map(s=>`<option value="${s}">${esc(names[s])}</option>`).join('')}</select></label><label>Основание без персональных данных<input name="reason" required minlength="3" maxlength="240"></label><label>Подтверждение события<input name="evidence_ref" pattern="EVID-[A-Za-z0-9_-]+" maxlength="100"></label><label>Owner approval для уже выполненной передачи застройщику<input name="owner_approval_ref" pattern="EVID-[A-Za-z0-9_-]+" maxlength="100"></label><p class="muted">Форма записывает доказанное событие. Она не отправляет сообщение застройщику. Защита клиента в этой форме не назначается автоматически.</p><button type="submit">Записать переход</button><p role="status"></p></form>`;
 document.querySelector('#status').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{const fields=Object.fromEntries([...new FormData(e.target)].filter(([,v])=>v));const r=await api('/admin/leads/'+encodeURIComponent(id)+'/status',{...fields,version:lead.version});lead.version=r.version;output.className='success';output.textContent=`Статус записан: ${names[r.status]||r.status}. Версия ${r.version}.`;try{await detail(id);}catch{output.textContent+=' Запись сохранена; журнал временно не обновился.';}});};
}
async function applicationCard(id,isOperator){
 const d=await api((isOperator?'/admin':'')+'/applications/'+encodeURIComponent(id)),a=d.application;
 root.innerHTML=title(a.company,a.city)+`<div class="panel"><p>${esc(names[a.status]||a.status)} · версия ${a.version}</p><p>Получено: ${esc(a.created_at)}</p><code>${esc(a.id)}</code><p>Квалификация и onboarding не означают активацию или регистрацию клиента у застройщика.</p></div><h2>История</h2>${d.events.map(e=>`<div class="row"><strong>${esc(names[e.status]||e.status)}</strong><p>${esc(e.created_at)}</p>${isOperator?`<p>${esc(e.reason)}</p>`:''}</div>`).join('')||'<p>Для ранее полученной заявки история ещё не записывалась.</p>'}`;
 const back=document.createElement('button');back.className='secondary';back.dataset.appBack='';back.textContent=isOperator?'К очереди заявок':'Мои заявки';back.onclick=()=> (isOperator?operator():application()).catch(e=>message(e.message));root.prepend(back);
 if(isOperator){const manage=document.createElement('button');manage.dataset.appAccess='';manage.textContent='Подключение и доступ';manage.onclick=()=>agencies('',a).catch(e=>message(e.message));root.append(manage);
  const contact=document.createElement('div');contact.className='panel';contact.innerHTML=`<h2>Связь с агентством</h2><p>${esc(a.name)} · ${esc(a.email)}</p><div class="actions"><a class="button secondary" href="mailto:${encodeURIComponent(a.email)}?subject=${encodeURIComponent('МИРА — заявка '+a.company)}">Подготовить письмо</a><a class="button secondary" href="https://wegc.fund/mira/documents/" target="_blank" rel="noopener noreferrer">Шаблоны документов ↗</a></div><p class="muted">Письмо откроется в твоей почте. Отправка и вложения — после твоей проверки. Шаблоны требуют заполнения и согласования; это не подписанные договоры.</p>`;root.append(contact);
 }
 if(!isOperator||!d.allowed_transitions.length)return;
 root.innerHTML+=`<h2>Обработка заявки</h2><form id="application-review" class="panel"><label>Следующий этап<select name="status">${d.allowed_transitions.map(s=>`<option value="${esc(s)}">${esc(names[s]||s)}</option>`).join('')}</select></label><label>Основание без персональных данных<input name="reason" required minlength="3" maxlength="240"></label><label>Подтверждение квалификации / onboarding<input name="evidence_ref" pattern="EVID-[A-Za-z0-9_-]+" maxlength="100"></label><label>ID агентства — только при завершении onboarding<input name="agency_id" pattern="[A-Za-z0-9_-]+" maxlength="100"></label><p class="muted">Не выдаёт права, не подписывает договор и не отправляет сообщения. Завершение onboarding требует действующего договора и привязанного владельца.</p><button type="submit">Записать этап</button><p role="status"></p></form>`;
 root.querySelector('[data-app-back]').onclick=()=>operator().catch(e=>message(e.message));
 root.querySelector('[data-app-access]').onclick=()=>agencies('',a).catch(e=>message(e.message));
 if(d.allowed_transitions.includes('qualified'))root.append(evidenceForm('application_qualification',{entity_id:a.id}));
 if(d.allowed_transitions.includes('onboarded')){
  const proofButton=document.createElement('button');proofButton.textContent='Добавить подтверждение подключения';proofButton.onclick=()=>{
   const agency=root.querySelector('#application-review [name=agency_id]').value.trim();
   if(!agency){root.querySelector('#application-review [role=status]').textContent='Сначала укажи ID подключённого агентства.';return;}
   if(!root.querySelector('[data-proof=agency_onboarding]'))root.append(evidenceForm('agency_onboarding',{entity_id:a.id,agency_id:agency}));
  };root.append(proofButton);
 }
 const review=root.querySelector('#application-review');
 review.elements.agency_id.oninput=()=>{root.querySelector('[data-proof=agency_onboarding]')?.remove();review.elements.evidence_ref.value='';};
 const updateReviewFields=()=>{const stage=review.elements.status.value;for(const name of ['evidence_ref','agency_id']){const input=review.elements[name],needed=name==='agency_id'?stage==='onboarded':['qualified','onboarded'].includes(stage);input.disabled=!needed;input.required=needed;input.closest('label').hidden=!needed;}};
 review.elements.status.onchange=updateReviewFields;updateReviewFields();
 document.querySelector('#application-review').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{
  const fields=Object.fromEntries([...new FormData(e.target)].filter(([,v])=>v));
  const r=await api('/admin/applications/'+encodeURIComponent(id)+'/status',{...fields,version:a.version});a.version=r.version;
  output.className='success';output.textContent=`Записано: ${names[r.status]||r.status}. Ничего не отправлялось.`;
  try{await applicationCard(id,true);}catch{output.textContent+=' Карточка не обновилась; запись уже сохранена.';}
 });};
}
// Agency administration uses the authenticated applicant subject returned by the
// server. There is no free-form identity field or automatic contract evidence.
async function agencies(cursor='',app=null){
 const d=await api('/admin/agencies'+(cursor?'?cursor='+encodeURIComponent(cursor):''));
 root.innerHTML=title('Доступ агентствам','Создай карточку, проверь договор и назначь представителя из его заявки.')+
 `<div class="actions"><button id="back-operator" class="secondary">К очереди заявок</button></div>`+
 (app?`<p>Заявка: <strong>${esc(app.company)}</strong> · ${esc(app.email)}. Выбери агентство ниже или создай новую карточку.</p>`:'')+
 `<form id="agency-create" class="panel"><h2>Новое агентство</h2><div class="form-grid"><label>Название<input name="name" required maxlength="120" value="${esc(app?.company||'')}"></label><label>Город<input name="city" required maxlength="120" value="${esc(app?.city||'')}"></label></div><p class="muted">Карточка создаётся со статусом «На проверке». Доступ ещё не выдаётся.</p><button type="submit">Создать карточку</button><p role="status"></p></form><h2>Агентства</h2>`+
 d.records.map(a=>`<div class="row"><strong>${esc(a.name)}</strong><p>${esc(a.city)} · ${esc({pending:'На проверке',active:'Активно',suspended:'Приостановлено'}[a.status])}</p><button data-agency="${esc(a.id)}">Управлять доступом</button></div>`).join('');
 document.querySelector('#back-operator').onclick=()=>operator().catch(e=>message(e.message));
 root.querySelectorAll('[data-agency]').forEach(b=>b.onclick=()=>agencyCard(b.dataset.agency,app).catch(e=>message(e.message)));
 let attempt=null;
 document.querySelector('#agency-create').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{
  const f=Object.fromEntries(new FormData(e.target)),serialized=JSON.stringify(f);
  if(attempt?.serialized!==serialized)attempt={id:crypto.randomUUID(),serialized};
  const r=await api('/admin/agencies',{id:attempt.id,...f,status:'pending'});
  output.textContent='Карточка создана.';await agencyCard(r.id,app);
 });};
 if(d.next_cursor){const b=document.createElement('button');b.textContent='Следующие агентства';b.onclick=()=>agencies(d.next_cursor,app).catch(e=>message(e.message));root.append(b);}
}
function evidenceForm(kind,scope){
 const form=document.createElement('form');form.className='panel';form.dataset.proof=kind;
 form.innerHTML=`<h3>${esc({agency_agreement:'Подтверждение договора',application_qualification:'Подтверждение квалификации',agency_onboarding:'Подтверждение подключения'}[kind])}</h3><label>Номер подтверждения<input name="id" required pattern="EVID-[A-Za-z0-9_-]+" maxlength="100" placeholder="EVID-…"></label><label>Ссылка на проверенный документ в закрытом архиве<input name="storage_ref" required maxlength="240" placeholder="vault:номер-документа"></label><div class="form-grid"><label>Дата проверки<input name="verified_at" type="datetime-local" required></label><label>Действует до, если указан срок<input name="expires_at" type="datetime-local"></label></div><label><input name="reviewed" type="checkbox" required>Я проверил документ и его соответствие этой заявке / агентству.</label><p class="muted">Записывается ссылка на документ. Сам документ сюда не загружается.</p><button type="submit">Сохранить подтверждение</button><p role="status"></p>`;
 form.onsubmit=e=>{e.preventDefault();withForm(form,async output=>{
  const f=Object.fromEntries(new FormData(form));
  const r=await api('/admin/evidence',{id:f.id,kind,...scope,storage_ref:f.storage_ref,verified:true,verified_at:new Date(f.verified_at).toISOString(),...(f.expires_at?{expires_at:new Date(f.expires_at).toISOString()}:{})});
  output.className='success';output.textContent=`Подтверждение ${r.id} сохранено.`;
  const input=root.querySelector(kind==='agency_agreement'?'#agency-state [name=agreement_ref]':'#application-review [name=evidence_ref]');if(input)input.value=r.id;
 });};return form;
}
async function agencyCard(id,app=null,cursor=''){
 const d=await api('/admin/agencies/'+encodeURIComponent(id)+(cursor?'?cursor='+encodeURIComponent(cursor):'')),a=d.agency;
 root.innerHTML=title(a.name,a.city)+`<div class="actions"><button id="back-agencies" class="secondary">Все агентства</button>${app?'<button id="back-application" class="secondary">Вернуться к заявке</button>':''}</div><p>Договор: ${d.agreement_current?'подтверждение актуально':'требуется проверка'}</p><code>${esc(a.id)}</code><form id="agency-state" class="panel"><h2>Статус агентства</h2><label>Статус<select name="status">${[['pending','На проверке'],['active','Активно'],['suspended','Приостановлено']].map(([v,l])=>`<option value="${v}" ${a.status===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Подтверждение договора<input name="agreement_ref" pattern="EVID-[A-Za-z0-9_-]+" value="${esc(a.agreement_ref||'')}"></label><p class="muted">Активация требует актуального подтверждения договора. Приостановка закрывает доступ агентства к рабочим данным.</p><button type="submit">Сохранить статус</button><p role="status"></p></form><div id="agreement-proof"></div><h2>Представители</h2><div id="agency-members"></div><div id="owner-binding"></div><h2>Журнал изменений</h2><div id="agency-audit"></div>`;
 document.querySelector('#back-agencies').onclick=()=>agencies('',app).catch(e=>message(e.message));
 if(app)document.querySelector('#back-application').onclick=()=>applicationCard(app.id,true).catch(e=>message(e.message));
 document.querySelector('#agreement-proof').append(evidenceForm('agency_agreement',{agency_id:id}));
 document.querySelector('#agency-state').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{
  const f=Object.fromEntries(new FormData(e.target));await api('/admin/agencies',{id,name:a.name,city:a.city,status:f.status,...(f.agreement_ref?{agreement_ref:f.agreement_ref}:{})});
  output.className='success';output.textContent='Статус сохранён.';await agencyCard(id,app);
 });};
 const members=document.querySelector('#agency-members');
 members.innerHTML=d.members.records.map(m=>`<form class="panel member-access" data-subject="${esc(m.subject)}"><p>${esc(m.role==='agency_owner'?'Руководитель':'Брокер')} · ${m.active?'Доступ включён':'Доступ выключен'}</p><code>${esc(m.subject)}</code><label><input type="checkbox" required>Подтверждаю ${m.active?'отзыв':'восстановление'} доступа этого представителя.</label><button type="submit">${m.active?'Отозвать доступ':'Восстановить доступ'}</button><p role="status"></p></form>`).join('')||'<p>Представители ещё не назначены.</p>';
 members.querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();withForm(f,async output=>{const m=d.members.records.find(x=>x.subject===f.dataset.subject);await api('/admin/memberships',{subject:m.subject,agency_id:id,role:m.role,active:!m.active});output.textContent='Доступ обновлён.';await agencyCard(id,app);});});
 if(d.members.next_cursor){const b=document.createElement('button');b.textContent='Следующие представители';b.onclick=()=>agencyCard(id,app,d.members.next_cursor).catch(e=>message(e.message));members.append(b);}
 if(app){
  const target=document.querySelector('#owner-binding');
  target.innerHTML=`<form id="bind-owner" class="panel"><h3>Представитель из заявки</h3><p>${esc(app.name)} · ${esc(app.email)}</p><p>Агентство: <strong>${esc(a.name)}</strong></p><label><input type="checkbox" required>Полномочия представителя проверены; назначить его руководителем этого агентства.</label><button type="submit">Назначить представителя</button><p role="status"></p></form>`;
  target.querySelector('form').onsubmit=e=>{e.preventDefault();withForm(e.target,async output=>{await api('/admin/memberships',{subject:app.subject,agency_id:id,role:'agency_owner',active:true});output.className='success';output.textContent='Представитель назначен. Итоговый этап подключения запиши в заявке.';});};
 }
 await auditHistory(document.querySelector('#agency-audit'),'agency',id);
 for(const form of members.querySelectorAll('.member-access')){const history=document.createElement('div');form.after(history);await auditHistory(history,'membership',form.dataset.subject);}
}

async function auditHistory(target,type,id,after=null){
 const control=document.createElement('button');control.className='secondary';control.textContent=after===null?'Загрузить журнал':'Ещё события';
 const load=async()=>{control.disabled=true;try{
  const history=await api('/admin/audit?entity_type='+type+'&entity_id='+encodeURIComponent(id)+'&limit=50'+(after===null?'':'&after_version='+after));
  control.remove();if(!history.records.length&&after===null)target.append(document.createTextNode('Изменений нет.'));
  for(const event of history.records){const row=document.createElement('div');row.className='row';row.innerHTML=`<strong>${esc(event.status)}</strong><p>${esc(event.created_at)} · версия ${event.version}</p>`;target.append(row);}
  if(history.next_after_version!==null)await auditHistory(target,type,id,history.next_after_version);
 }catch(e){control.textContent=e.message+' — повторить';control.disabled=false;}};
 control.onclick=load;target.append(control);if(after===null&&type==='agency')await load();
}

async function operator(cursor=''){
 if(session.membership?.role!=='operator')throw new Error('Раздел доступен только оператору.');
 const dashboard=await api('/admin/dashboard'),apps=await api('/admin/applications'+(cursor?'?cursor='+encodeURIComponent(cursor):''));
 root.innerHTML=title('Операционный контроль','Только наблюдаемые записи подключённой базы. Исследовательские контакты и демо не считаются подключёнными агентствами.')+
 `<div class="actions"><button id="manage-agencies">Доступ агентствам</button><a href="/mira/research/">Исследовательская база</a></div><div class="facts">${[['Заявки',dashboard.applications],['Агентства',dashboard.agencies],['Клиенты',dashboard.leads],['События сделок',dashboard.deal_events],['Платёжные запросы',dashboard.payment_requests]].map(([label,rows])=>`<div><h2>${label}</h2>${rows.map(r=>`<p>${esc(names[r.status||r.stage]||r.status||r.stage)}: <strong>${r.count}</strong></p>`).join('')||'<p>В этой базе записей нет.</p>'}</div>`).join('')}</div><h2>Очередь заявок</h2>${apps.records.map(a=>`<div class="row"><strong>${esc(a.company)} · ${esc(a.city)}</strong><p>${esc(a.name)} · ${esc(a.email)}</p><p>${esc(names[a.status]||a.status)}</p><button type="button" data-review="${esc(a.id)}">Открыть и обработать</button></div>`).join('')||'<p>Полученных заявок нет.</p>'}`;
 document.querySelector('#manage-agencies').onclick=()=>agencies().catch(e=>message(e.message));
 root.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>applicationCard(b.dataset.review,true).catch(e=>message(e.message)));
 if(apps.next_cursor){const b=document.createElement('button');b.textContent='Следующая страница заявок';b.onclick=()=>operator(apps.next_cursor).catch(e=>message(e.message));root.append(b);}
}
async function render(){if(!session)return;root.textContent='Загрузка…';try{await ({application,profile,projects,leads,operator}[section]||application)();}catch(e){message(e.message);}}
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;document.querySelectorAll('[data-section]').forEach(x=>x.setAttribute('aria-current',x===b?'page':'false'));render();});
try{session=await api('/session');document.querySelector('[data-section=operator]').hidden=session.membership?.role!=='operator';document.querySelectorAll('[data-membership]').forEach(el=>el.hidden=!session.membership);document.querySelector('[data-section=application]').setAttribute('aria-current','page');await render();}catch(e){message(e.message);}
