import {validateCatalogue} from '../catalog-core.mjs';
/** Country-aware public catalogue. Read-only public JSON, local shortlist only. */
import {MARKETS,PROPERTY_TYPES,PAGE_SIZE,MAX_SELECTION,normalize,marketFromPath,isCatalogueIndex,safeReturnPath,validateExpansion,validateDiscovery,combineProjects,marketProjects,filterProjects,paginate,safeSelection,toggleSelection} from './market-core.mjs';
const $=id=>document.getElementById(id),KEY='mira-research-selection-v1',RETURN='mira-catalog-return';
const market=marketFromPath(location.pathname),country=MARKETS[market];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let all=[],rows=[],selection=[],pendingSelection=[],state={q:'',district:'',kind:'',family:'',page:1},loaded=false;
const controls=['search','district','kind','family','filters-reset'];
const KIND={villa:'Виллы / дома',condo:'Кондоминиумы / апартаменты',mixed:'Смешанный проект',hotel:'Гостиничный формат'};
function readSaved(){for(const storage of [()=>sessionStorage,()=>localStorage])try{const raw=storage().getItem(KEY);if(raw){const value=JSON.parse(raw);return Array.isArray(value)?value:[];}}catch{}return [];}
function saveSelection(){const combined=[...selection,...pendingSelection].slice(0,MAX_SELECTION);try{localStorage.setItem(KEY,JSON.stringify(combined));try{sessionStorage.removeItem(KEY);}catch{}return;}catch{}try{sessionStorage.setItem(KEY,JSON.stringify(combined));}catch{toast('Сохранение браузера недоступно. Скачайте подборку перед закрытием страницы.');}}
function toast(msg){const e=$('toast');if(e){e.textContent=msg;e.hidden=false;e.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>{e.hidden=true;e.classList.remove('visible');},3000);}}
function cover(p){const meta=MARKETS[p.market]||MARKETS.phuket;return `<figure class="market-visual direction-photo ${esc(p.market)}"><img src="/images/mira-directions/${esc(p.market)}.jpg" alt="${meta.name} — фото направления" width="1280" height="800" loading="lazy" decoding="async"><figcaption>${meta.name} · фото направления, не проекта</figcaption></figure>`;}
function phuketCover(p){return '/images/hero/hero-phuket-'+(p.kind==='villa'?'aerial-sunset':'bay-karst')+'-m.jpg';}
function visual(p){
 if(p.market!=='phuket')return p.image?`<figure class="market-visual"><img src="${esc(p.image)}" alt="${esc(p.name)} — материал проекта" loading="lazy" decoding="async" width="1400" height="875"><figcaption>${esc(p.imageCaption)}</figcaption></figure><template class="image-recovery">${cover(p)}</template>`:cover(p);
 const image=p.image||phuketCover(p);return `<figure class="card-image"><img src="${esc(image)}" data-fallback="${phuketCover(p)}" alt="${esc(p.image?'Визуализация '+p.name:'Иллюстрация МИРА — Пхукет')}" width="1200" height="750" loading="lazy" decoding="async"><figcaption>${p.image?'Визуализация проекта':'МИРА / Пхукет · обложка каталога'}</figcaption></figure>`;
}
function card(p){const href='/mira/catalog/projects/'+p.id+'/',selected=selection.includes(p.id);return `<article class="project-card" data-market="${esc(p.market)}"><a class="visual-link" href="${href}" aria-label="Подробнее: ${esc(p.name)}">${visual(p)}</a><div class="card-body"><p class="tag">${esc(p.district||MARKETS[p.market].name)} · ${esc(p.typeLabel||KIND[p.kind]||'Недвижимость')}</p><h2><a href="${href}">${esc(p.name)}</a></h2><p class="family">${esc(p.family||'Коллекция проектов Пхукета')}</p>${p.summary?`<p class="market-card-summary">${esc(p.summary)}</p>`:''}<p class="availability">Наличие и условия — по запросу</p><div class="card-actions"><a href="${href}">Подробнее ↗</a><button class="add secondary" data-add="${esc(p.id)}" type="button" aria-pressed="${selected}">${selected?'В подборке ✓':'В подборку +'}</button></div></div></article>`;}
function recoverImage(img){
 if(img.closest('.direction-photo')){img.hidden=true;return;}
 const tpl=img.closest('a, .detail-grid > div')?.querySelector('template.image-recovery');
 if(tpl){img.closest('figure')?.replaceWith(tpl.content.cloneNode(true));tpl.remove();return;}
 if(!img.dataset.fallback)return;
 const figure=img.closest('figure');
 if(!img.dataset.recovered){img.dataset.recovered='1';img.src=img.dataset.fallback;img.alt='Иллюстрация МИРА — Пхукет';if(figure?.querySelector('figcaption'))figure.querySelector('figcaption').textContent='МИРА / Пхукет · обложка каталога';}
 else{img.hidden=true;figure?.classList.add('branded-cover');}
}
function bindImages(){for(const img of document.querySelectorAll('img')){if(img.dataset.marketBound)continue;img.dataset.marketBound='1';img.addEventListener('error',()=>recoverImage(img));if(img.complete&&!img.naturalWidth)recoverImage(img);}}
function readState(){const q=new URLSearchParams(location.search);state={q:(q.get('q')||'').slice(0,120),district:q.get('district')||'',kind:q.get('kind')||'',family:q.get('family')||'',page:Number(q.get('page'))||1};}
function writeURL(push=true){if(!isCatalogueIndex(location.pathname))return;const q=new URLSearchParams();for(const k of ['q','district','kind','family'])if(state[k])q.set(k,state[k]);if(state.page>1)q.set('page',String(state.page));const next=location.pathname+(q.size?'?'+q:'');if(next!==location.pathname+location.search)history[push?'pushState':'replaceState'](null,'',next);}
function restoreControls(){for(const [id,key] of [['search','q'],['district','district'],['kind','kind'],['family','family']])if($(id))$(id).value=state[key];}
function options(id,values,labels){const el=$(id);if(!el)return;while(el.options.length>1)el.remove(1);for(const value of [...new Set(values.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ru'))){const o=document.createElement('option');o.value=value;o.textContent=labels?.[value]||value;el.append(o);}}
function render(push=true){if(!$('cards'))return;const result=paginate(filterProjects(rows,state),state.page);state.page=result.page;$('cards').innerHTML=result.items.map(card).join('')||'<p class="empty">По этим условиям проектов нет. Измените фильтры.</p>';if($('result-count'))$('result-count').textContent=`Найдено: ${result.total} · ${country.name}`;if($('page-status'))$('page-status').textContent=`${result.page} / ${result.pages}`;if($('prev'))$('prev').disabled=result.page<=1;if($('next'))$('next').disabled=result.page>=result.pages;writeURL(push);bindImages();syncSelection();}
function syncSelection(){for(const b of document.querySelectorAll('[data-add]')){const known=all.some(p=>p.id===b.dataset.add),active=selection.includes(b.dataset.add);b.disabled=!loaded||!known;b.setAttribute('aria-pressed',String(active));b.textContent=active?'В подборке ✓':'В подборку +';}if($('shortlist-open'))$('shortlist-open').hidden=selection.length===0;if($('shortlist-count'))$('shortlist-count').textContent=String(selection.length);if($('shortlist-download'))$('shortlist-download').disabled=!selection.length;if($('shortlist-clear'))$('shortlist-clear').disabled=!selection.length;if($('shortlist-items'))$('shortlist-items').innerHTML=selection.map(id=>{const p=all.find(x=>x.id===id);return `<article class="shortlist-item"><div><a href="/mira/catalog/projects/${esc(id)}/">${esc(p.name)}</a><p>${MARKETS[p.market].name} · ${esc(p.district)} · ${esc(p.family||'')}</p></div><button type="button" class="secondary" data-remove="${esc(id)}" aria-label="Удалить ${esc(p.name)}">Удалить ×</button></article>`;}).join('')||'<p>Подборка пуста. Выберите проекты в каталоге.</p>';}
function download(){if(!selection.length)return;const lines=['МИРА — предварительная подборка','Не отправлена. Наличие и условия подтверждаются отдельно.',''];for(const id of selection){const p=all.find(x=>x.id===id);lines.push(p.name,MARKETS[p.market].country+' / '+MARKETS[p.market].name+' / '+(p.district||''),p.family||'',location.origin+'/mira/catalog/projects/'+id+'/','');}const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=selection.some(id=>all.find(p=>p.id===id).market!=='phuket')?'mira-international-selection.txt':'mira-phuket-selection.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function openDialog(){const d=$('shortlist');if(!d)return;syncSelection();if(typeof d.showModal==='function')d.showModal();else{d.setAttribute('open','');d.hidden=false;}}
function closeDialog(){const d=$('shortlist');if(!d)return;if(typeof d.close==='function')d.close();else d.removeAttribute('open');$('shortlist-open')?.focus();}
async function getJSON(url){const r=await fetch(url,{credentials:'omit',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Catalogue HTTP '+r.status);const text=await r.text();if(text.length>5000000)throw Error('Catalogue too large');return JSON.parse(text);}
async function load(){
 try{
  const [baseResult,extraResult,discoveryResult]=await Promise.allSettled([getJSON('/mira/catalog/data.json'),getJSON('/mira/catalog/markets/data.json'),getJSON('/mira/catalog/markets/discovery.json')]);
  if(baseResult.status!=='fulfilled')throw Error('Phuket feed unavailable');const base=validateCatalogue(baseResult.value);if(base.schemaVersion!==1||base.mode!=='public_research'||!Array.isArray(base.projects)||base.projects.length!==618)throw Error('Invalid Phuket source');
  let extra=null;try{if(extraResult.status==='fulfilled')extra=validateExpansion(extraResult.value);}catch{}
  let discovery=null;try{if(discoveryResult.status==='fulfilled')discovery=validateDiscovery(discoveryResult.value);}catch{}
  if((!extra&&['bali','dubai'].includes(market))||(!discovery&&['vietnam','montenegro'].includes(market)))throw Error('New market feed unavailable');
  all=extra?combineProjects(base.projects,extra,discovery):[...base.projects.map(p=>({...p,market:'phuket'})),...(discovery?.projects||[])];rows=marketProjects(all,market);
  const raw=readSaved();selection=safeSelection(raw,all);pendingSelection=raw.filter(id=>typeof id==='string'&&!all.some(p=>p.id===id)&&((!extra&&/^(bali|dubai)-[a-z0-9-]+$/.test(id))||(!discovery&&/^(vn|me)-[a-z0-9-]+$/.test(id)))).slice(0,MAX_SELECTION-selection.length);
  options('district',rows.map(p=>p.district));options('family',rows.map(p=>p.family));options('kind',rows.flatMap(p=>['vietnam','montenegro'].includes(p.market)?[p.kind]:(p.propertyTypes||[p.kind])),['phuket','vietnam','montenegro'].includes(market)?KIND:PROPERTY_TYPES);
  readState();restoreControls();loaded=true;for(const id of controls)if($(id))$(id).disabled=false;if($('load-error'))$('load-error').hidden=true;render(false);syncSelection();bindImages();

 }catch(e){loaded=false;if($('load-error')){$('load-error').hidden=false;$('load-error').textContent='Не удалось обновить каталог. Карточки ниже доступны; повторите загрузку позже.';}for(const id of controls)if($(id))$(id).disabled=true;bindImages();}
}
let searchTimer;
$('search')?.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.q=$('search').value.slice(0,120);state.page=1;render();},100);});
for(const id of ['district','family','kind'])$(id)?.addEventListener('change',()=>{state[id]=$(id).value;state.page=1;render();});
$('filters-reset')?.addEventListener('click',()=>{clearTimeout(searchTimer);state={q:'',district:'',kind:'',family:'',page:1};restoreControls();render();});
$('prev')?.addEventListener('click',()=>{state.page--;render();$('cards')?.scrollIntoView({block:'start'});});$('next')?.addEventListener('click',()=>{state.page++;render();$('cards')?.scrollIntoView({block:'start'});});
$('shortlist-open')?.addEventListener('click',openDialog);$('shortlist-close')?.addEventListener('click',closeDialog);$('shortlist-download')?.addEventListener('click',download);
$('shortlist-clear')?.addEventListener('click',()=>{selection=[];pendingSelection=[];saveSelection();syncSelection();if($('shortlist-message'))$('shortlist-message').textContent='Подборка очищена.';});
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),remove=e.target.closest('[data-remove]');if(add&&!add.disabled&&loaded){const id=add.dataset.add,old=selection.length;if(!selection.includes(id)&&selection.length+pendingSelection.length>=MAX_SELECTION){toast('В подборке не больше '+MAX_SELECTION+' проектов.');return;}selection=toggleSelection(selection,id,all);saveSelection();syncSelection();toast(selection.length===old?'В подборке не больше '+MAX_SELECTION+' проектов.':selection.includes(id)?'Проект добавлен в подборку.':'Проект удалён из подборки.');}else if(remove&&loaded){selection=selection.filter(x=>x!==remove.dataset.remove);saveSelection();syncSelection();}const link=e.target.closest('a[href]');if(link&&isCatalogueIndex(location.pathname)&&link.getAttribute('href')?.startsWith('/mira/catalog/projects/'))try{sessionStorage.setItem(RETURN,location.pathname+location.search);}catch{}});
window.addEventListener('popstate',()=>{if(loaded){readState();restoreControls();render(false);}});
window.addEventListener('storage',e=>{if((e.key===KEY||e.key===null)&&loaded){selection=safeSelection(readSaved(),all);syncSelection();}});
window.addEventListener('pageshow',e=>{if(e.persisted&&loaded){selection=safeSelection(readSaved(),all);syncSelection();}});
// Static detail links use an explicit marker so even a pre-script click restores state.
if(isCatalogueIndex(location.pathname)&&new URLSearchParams(location.search).get('restore')==='1'){let saved;try{saved=sessionStorage.getItem(RETURN);}catch{}history.replaceState(null,'',safeReturnPath(saved,market,location.origin)||country.path);}
// Back navigation must be ready before the asynchronous catalogue feeds finish.
for(const a of document.querySelectorAll('[data-catalog-back]')){let saved;try{saved=sessionStorage.getItem(RETURN);}catch{}const good=safeReturnPath(saved,market,location.origin);a.setAttribute('href',good||country.path);}
load();
