#!/usr/bin/env python3
"""Build three original Russian B2B funnels. No customer intake or invented sales proof."""
from pathlib import Path
import html,json
ROOT=Path(__file__).resolve().parents[1]
def esc(v):return html.escape(str(v),quote=True)
VARIANTS={
 'go':{'tone':'direct','label':'Прямо и энергично','title':'Откройте клиентам зарубежную недвижимость.','headline':'Откройте клиентам<br><em>зарубежную</em><br>недвижимость.','lead':'Не отдавайте зарубежный запрос другому брокеру. Добавьте Пхукет в предложение своего агентства — клиент и ваш бренд остаются с вами.','cta':'Посмотреть проекты','eyebrow':'ДЛЯ АГЕНТСТВ НЕДВИЖИМОСТИ','section':'Клиент спросил о Пхукете.<br>У вас есть следующий шаг.'},
 'business':{'tone':'practical','label':'Понятно и по делу','title':'Пхукет — ещё одно направление вашего агентства.','headline':'Пхукет — ещё одно<br><em>направление</em><br>вашего агентства.','lead':'Каталог, договорный процесс и работа с застройщиком. Начните с одного запроса — без открытия зарубежного офиса и замены вашей CRM.','cta':'Выбрать проект под запрос','eyebrow':'МИРА / ДЛЯ РУКОВОДИТЕЛЯ И КОМАНДЫ','section':'Не новая профессия.<br>Новое предложение клиенту.'},
 'corporate':{'tone':'corporate','label':'Сдержанно и системно','title':'Зарубежное направление под управлением вашего агентства.','headline':'Зарубежное направление.<br><em>Под управлением</em><br>вашего агентства.','lead':'Подключайте международное предложение через единый процесс: определённые роли, согласованные проекты и последовательные статусы работы с клиентом.','cta':'Изучить предложение Пхукета','eyebrow':'МИРА / МЕЖДУНАРОДНАЯ ИНФРАСТРУКТУРА','section':'Ваше агентство управляет<br>отношениями с клиентом.'}}
LINKS='<a href="/mira/catalog/">Проекты Пхукета</a><a href="/mira/documents/">Документы</a><a href="#how">Как работаем</a>'
def head(v):
 return f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"><title>{esc(v['title'])} — МИРА</title><meta name="description" content="{esc(v['lead'])}"><link rel="stylesheet" href="/mira/campaign/campaign.css"><script type="module" src="/mira/campaign/campaign.mjs"></script></head><body class="{v['tone']}"><a class="skip" href="#main">К содержанию</a><header class="top wrap"><a class="brand" href="/mira/go/">МИРА<span>Ваш клиент. Ваш бренд.</span></a><nav aria-label="Основная навигация">{LINKS}<a class="button compact" href="https://pilot.wegc.fund/mira/request/">Подать заявку ↗</a></nav></header>'''
def qualifier():
 return '''<section class="start wrap" id="start"><div><p class="eyebrow">НАЧНИТЕ С ВАШЕЙ ЗАДАЧИ</p><h2>Куда идём<br>с вашим агентством?</h2><p class="lead">Оставьте рабочие контакты агентства. Заявка поступит команде МИРА, а ответ придёт на рабочий email.</p><p><a class="button" href="https://pilot.wegc.fund/mira/request/">Подать заявку агентства ↗</a></p><p class="fine">Приглашение не требуется; данные покупателей здесь не принимаются. Договор и порядок работы согласуем отдельно. Справа можно предварительно составить личный план — он не отправляется команде.</p></div><div class="qualifier"><form id="campaign-form"><fieldset disabled><legend>Личный план знакомства</legend><label>Как работаете сейчас?<select name="model" required><option value="">Выберите вариант</option><option value="new_direction">Пока продаём только в своём регионе</option><option value="overseas_desk">Уже продаём зарубежную недвижимость</option><option value="thailand_desk">Уже работаем с Таиландом</option><option value="network">Представляем сеть / франшизу</option></select></label><label>Что нужно в первую очередь?<select name="goal" required><option value="">Выберите задачу</option><option value="client_request">Есть запрос клиента</option><option value="build_direction">Хотим добавить направление</option><option value="improve_process">Нужна помощь на отдельном этапе</option><option value="explore">Сначала разобраться</option></select></label><label>Кто займётся направлением?<select name="owner" required><option value="">Выберите роль</option><option value="decision_maker">Я — владелец / руководитель</option><option value="assigned_manager">У нас есть менеджер</option><option value="independent_broker">Я — независимый брокер</option><option value="not_assigned">Ещё не определились</option></select></label><button id="prepare" type="submit">Получить план подключения ↗</button></fieldset></form><p id="form-message" role="status"></p><section id="plan" hidden><h3 id="plan-title" tabindex="-1"></h3><p id="plan-description"></p><ol id="plan-steps"></ol><p class="fine" id="plan-boundary"></p><div class="actions"><a class="button" href="/mira/catalog/">Перейти к проектам</a><button id="download" type="button" class="secondary">Скачать бриф ↓</button></div></section><noscript><p>План требует JavaScript. <a href="/mira/documents/agency-agreement.html">Условия сотрудничества доступны без скриптов.</a></p></noscript></div></section>'''
def illustration(tone):
 if tone=='direct':
  return '''<div class="door-scene" aria-label="Визуальная метафора нового направления"><div class="destination">ПХУКЕТ <span>↗</span></div><div class="doorframe"><div class="door-view"></div><div class="door-leaf"><span class="door-mark">М</span><span class="door-handle"></span></div></div><div class="scene-ticket"><span>Ваше агентство</span><b>Новая география ↗</b></div><p class="image-note">Иллюстрация направления, не предложение конкретного объекта</p></div>'''
 if tone=='practical':
  return '''<div class="work-scene"><div class="work-top"><b>Рабочая задача</b><span>Пхукет</span></div><div class="work-image"><p>От запроса<br>к выбору проекта.</p><small>Архивная визуализация</small></div><div class="work-route"><span>01 <b>Подборка</b></span><span>02 <b>Условия</b></span><span>03 <b>Регистрация*</b></span></div><p class="fine">* После допуска проекта. Схема процесса, не реальная клиентская заявка.</p><a href="/mira/catalog/">Открыть настоящий каталог ↗</a></div>'''
 return '''<div class="control-scene"><p>ЕДИНЫЙ КОНТУР СОТРУДНИЧЕСТВА</p><div class="control-row"><span>Агентство</span><b>Клиент и коммуникация</b></div><div class="control-row"><span>МИРА</span><b>Международный процесс</b></div><div class="control-row"><span>Застройщик</span><b>Объект и подтверждение</b></div><a href="/mira/documents/agency-agreement.html">Рамочный договор и приложения ↗</a></div>'''
def build_page(v):
 hero=f'''<main id="main"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow">{v['eyebrow']}</p><h1>{v['headline']}</h1><p class="lead">{v['lead']}</p><div class="actions"><a class="button" href="/mira/catalog/">{v['cta']} ↗</a><a class="text-link" href="https://pilot.wegc.fund/mira/request/">Подать заявку →</a></div><p class="hero-fine">Выберите проекты. Сохраните подборку. Обсудите следующий шаг.</p></div>{illustration(v['tone'])}</section>'''
 if v['tone']=='direct':
  opening='''<section class="impact"><div class="wrap"><h2>Клиент остаётся вашим.<br><span>География — меняется.</span></h2><a href="#how" class="round-arrow" aria-label="Как это работает">↓</a></div></section>'''
 elif v['tone']=='practical':
  opening='''<section class="benefit-line wrap"><div><b>Ваша CRM</b><span>Не переносите клиентскую базу</span></div><div><b>Ваш менеджер</b><span>Не отдавайте отношения с клиентом</span></div><div><b>Новый ассортимент</b><span>Начните с Пхукета</span></div></section>'''
 else:
  opening='''<section class="corporate-thesis wrap"><p>ПРИНЦИП МОДЕЛИ</p><h2>Не передача лида.<br>Расширение компетенций агентства.</h2><a href="/mira/documents/">Изучить договорную модель →</a></section>'''
 process=f'''<section class="section wrap" id="how"><div class="section-heading"><div><p class="eyebrow">КАК ЭТО УСТРОЕНО</p><h2>{v['section']}</h2></div><p>Вы консультируете покупателя под своим брендом. МИРА обеспечивает согласованный процесс работы с зарубежным предложением.</p></div><div class="process"><article><span class="step-no">01</span><h3>Выберите проекты</h3><p>Изучите каталог Пхукета, отберите подходящие направления и сформируйте предварительную подборку.</p><a href="/mira/catalog/">Открыть каталог ↗</a></article><article><span class="step-no">02</span><h3>Подготовьте подключение</h3><p>Определите задачу команды. Согласуйте договор, проект, правила регистрации и комиссию до рабочего запроса.</p><a href="https://pilot.wegc.fund/mira/request/">Обсудить подключение ↗</a></article></div><p class="fine">Подключение и работа с покупателем — по согласованным правилам выбранного проекта.</p></section>'''
 projects='''<section class="project-strip wrap"><div class="project-picture"><img src="/images/the-modeva-exterior-4-1.webp" alt="Архивная визуализация The Modeva" loading="lazy" width="900" height="560"><span>Архивная визуализация · The Modeva</span></div><div><p class="eyebrow">ПЕРВЫЙ РЫНОК — ПХУКЕТ</p><h2>Начните с места.<br>Не с нового офиса.</h2><p>Виллы и кондоминиумы, районы и группы девелоперов — в одном каталоге. Выбирайте проекты и собирайте свою подборку.</p><a class="button" href="/mira/catalog/">Найти проект ↗</a><p class="fine">Наличие и условия — по запросу. Первый рынок нашего агентского предложения — Пхукет. Условия работы в других направлениях уточняются отдельно.</p></div></section>'''
 roles='''<section class="section wrap roles"><div><p class="eyebrow">ЧТО ОСТАЁТСЯ У ВАС</p><h2>Клиент.<br>Команда.<br>Ваше имя.</h2><p>Не нужно представляться другим агентством. Сохраняйте отношения с покупателем и свою клиентскую базу.</p></div><div class="role-list"><details open><summary>Проекты и материалы</summary><p>Каталог для выбора и материалы с понятными условиями использования. Рабочие данные — после проверки конкретного проекта.</p></details><details><summary>Регистрация и статусы</summary><p>Согласованный путь от запроса до подтверждения застройщиком. Защита клиента действует только в пределах подтверждённых правил проекта.</p></details><details><summary>Договорная комиссия</summary><p>Доля агентства, событие начисления и порядок выплаты фиксируются отдельно. Публичная страница не заменяет согласованный коммерческий график.</p></details><details><summary>Платёжное сопровождение</summary><p>Отдельный запрос и проверка конкретной сделки. Средства покупателя и агентское вознаграждение не смешиваются.</p></details></div></section>'''
 proof='''<section class="documents-band"><div class="wrap"><div><p class="eyebrow">ДО СТАРТА — ВСЁ ПО ПУНКТАМ</p><h2>Условия можно прочитать.<br>Не только услышать.</h2></div><div><a href="/mira/documents/agency-agreement.html">Договор с агентством ↗</a><a href="/mira/documents/project-rules.html">Регистрация и защита клиента ↗</a><a href="/mira/documents/">Все документы и PDF ↗</a><p class="fine">Опубликованы переговорные проекты. Они не являются действующей офертой и не принимаются автоматически.</p></div></div></section>'''
 faq='''<section class="section wrap faq"><h2>Без лишних обещаний.<br>С понятным следующим шагом.</h2><details><summary>Это передача клиента другому агентству?</summary><p>Нет. Агентство сохраняет коммуникацию и свой бренд. Отдельные действия застройщика и правила регистрации согласуются по конкретному проекту.</p></details><details><summary>Можно сразу зарегистрировать покупателя?</summary><p>Регистрация покупателей сейчас выключена. Для её включения потребуется отдельный подтверждённый процесс по проекту и договору. Начните с подбора объектов и плана подключения. На публичном сайте данные покупателей не принимаются.</p></details><details><summary>Сколько зарабатывает агентство?</summary><p>Вознаграждение определяется только согласованным поручением и подтверждённой комиссией проекта. Универсальную ставку на все объекты мы не обещаем.</p></details><details><summary>Нужно ли менять CRM?</summary><p>Нет. Модель МИРА не требует переноса всей вашей клиентской базы. Для конкретного действия используется только согласованный необходимый объём данных.</p></details></section>'''
 end='''</main><footer class="wrap"><a class="brand" href="/mira/go/">МИРА</a><nav><a href="/mira/catalog/">Каталог</a><a href="/mira/documents/">Документы</a><a href="#how">Как работаем</a><a href="#start">План подключения</a></nav><p>МИРА / WEST EAST TRADE GROUP PTE. LTD. · Публичные материалы, не оферта. Рабочие подключения — после согласования.</p><button id="motion-toggle" class="motion-button" type="button" aria-pressed="false">Остановить движение</button></footer></body></html>'''
 return head(v)+hero+opening+process+projects+roles+proof+qualifier()+faq+end

def build(root=ROOT):
 for route,v in VARIANTS.items():
  path=root/'mira'/route;path.mkdir(parents=True,exist_ok=True);(path/'index.html').write_text(build_page(v),'utf-8')
 hub=root/'mira/launch';hub.mkdir(parents=True,exist_ok=True)
 cards=''.join(f'<a class="choice {v["tone"]}" href="/mira/{r}/"><span>0{i}</span><h2>{v["label"]}</h2><p>{v["title"]}</p><b>Открыть вариант ↗</b></a>' for i,(r,v) in enumerate(VARIANTS.items(),1))
 page=head(VARIANTS['practical'] if 'practical' in VARIANTS else VARIANTS['business'])+'''<main class="wrap review-hub" id="main"><p class="eyebrow">МАТЕРИАЛЫ ДЛЯ ВЛАДЕЛЬЦА</p><h1>Три разных способа<br>начать разговор.</h1><p class="lead">Первый — для холодного контакта и QR на выставке. Второй — для повседневной работы агентства. Третий — для руководителей и сетей. Варианты подготовлены, окончательное утверждение — за владельцем.</p><div class="choices">'''+cards+'''</div><section class="section"><h2>Всё для проверки запуска</h2><div class="hub-links"><a href="/mira/catalog/">Полный каталог Пхукета ↗</a><a href="/mira/documents/">Договор и документальный пакет ↗</a><a href="/mira/design/">Сохранённый редакционный дизайн ↗</a><a href="/mira/agency/">Предыдущая воронка ↗</a><a href="/mira/marketplace-design.html">Иллюстрированный демо-кабинет ↗</a><a href="/mira/exhibition/">Баннер и точный QR ↗</a></div><p class="fine">25 сентября — дата, указанная владельцем. Организатор и требования типографии отдельно не подтверждены. Полноценная регистрация ещё закрыта; сценарии демо не являются реальными клиентскими заявками.</p></section></main></body></html>'''
 (hub/'index.html').write_text(page,'utf-8')
 print(json.dumps({'landing_variants':list(VARIANTS),'owner_approved':False,'external_submissions':0}))
if __name__=='__main__':build()
