/** Full research catalogue. No personal-data intake, remote writes or persistent storage. */
export const PAGE_SIZE=24;
export const normalize=s=>String(s??'').normalize('NFKC').toLowerCase().replace(/ё/g,'е').trim();
export function validate(data){if(!data||data.version!==1||data.scope!=='research'||!Array.isArray(data.records)||data.count!==data.records.length||!data.count||data.count>5000||!/^[a-f0-9]{64}$/.test(data.sourceSha256))throw Error('invalid_catalog');const ids=new Set(),slugs=new Set();for(const r of data.records){if(!/^PHK-P-[a-f0-9]{12}$/.test(r.id)||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(r.slug)||ids.has(r.id)||slugs.has(r.slug)||r.registrationEnabled!==false||r.verifiedAt!==null)throw Error('invalid_record');for(const k of ['name','district','kind','family','basis'])if(typeof r[k]!=='string'||r[k].length>400)throw Error('invalid_field');if(r.image!==null&&!/^\/images\/[a-z0-9-]+\.webp$/.test(r.image))throw Error('invalid_image');if(Object.keys(r).some(k=>/price|commission|yield|income|exchange|availability/i.test(k)))throw Error('unexpected_financial_field');ids.add(r.id);slugs.add(r.slug);}return data;}
export function filter(records,{q='',district='',kind='',saved=false}={},selection=new Set()){const terms=normalize(q).slice(0,200).split(/\s+/).filter(Boolean);return records.filter(r=>(!district||r.district===district)&&(!kind||r.kind===kind)&&(!saved||selection.has(r.id))&&terms.every(t=>normalize(`${r.name} ${r.district} ${r.family} ${r.slug}`).includes(t)));}
export function paginate(records,requested=1){const pages=Math.max(1,Math.ceil(records.length/PAGE_SIZE)),page=Math.min(pages,Math.max(1,Number.isFinite(+requested)?Math.floor(+requested):1));return {page,pages,total:records.length,records:records.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE)};}
export function brief(records,selection){return ['МИРА / Подборка Пхукета','Это локальный бриф, не бронь, не регистрация и не подтверждение наличия.','Не добавляйте сюда персональные данные покупателей.','',...records.filter(r=>selection.has(r.id)).map(r=>`${r.name}\nРайон по источнику: ${r.district}\nhttps://wegc.fund/mira/phuket/project/${r.slug}/\nТребуется проверка предложения.\n`),'Договор и порядок работы: https://wegc.fund/mira/documents/'].join('\n');}
if(typeof document!=='undefined'&&document.getElementById('catalogue')){
const $=id=>document.getElementById(id),selection=new Set(),kinds={condo:'Кондоминиум',villa:'Вилла'};let data=null,page=1,request=null,timer,lastFocus=null;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const state=()=>({q:$('q').value,district:$('district').value,kind:$('kind').value,saved:$('saved').getAttribute('aria-pressed')==='true'});
function url(){const u=new URL(location.href),s=state();for(const k of ['q','district','kind'])s[k]?u.searchParams.set(k,s[k]):u.searchParams.delete(k);page>1?u.searchParams.set('page',page):u.searchParams.delete('page');history.replaceState({},'',u);}
function selectionUI(){for(const b of document.querySelectorAll('[data-save]')){const on=selection.has(b.dataset.save);b.textContent=on?'В подборке ✓':'+ В подборку';b.setAttribute('aria-pressed',String(on));}$('saved').textContent=`Подборка (${selection.size})`;$('download-selection').disabled=!selection.size;}
function save(r){const b=el('button','+ В подборку','save');b.type='button';b.dataset.save=r.id;b.setAttribute('aria-pressed',String(selection.has(r.id)));b.onclick=()=>{selection.has(r.id)?selection.delete(r.id):selection.add(r.id);if(state().saved)render();selectionUI();};return b;}
function visual(r){const f=el('figure',undefined,'project-image');if(r.image){const image=el('img');image.src=r.image;image.alt=`Архивная визуализация ${r.name}`;image.loading='lazy';image.decoding='async';image.width=640;image.height=400;f.append(image,el('figcaption','Архивная визуализация · не наличие'));image.onerror=()=>{f.replaceChildren(el('span','Изображение недоступно'));f.classList.add('placeholder');};}else{f.classList.add('placeholder');f.append(el('b','МИРА↗'),el('span','Изображение не опубликовано'));}return f;}
function open(r){lastFocus=document.activeElement;const c=$('detail-content');c.replaceChildren();const title=el('h2',r.name);title.id='project-title';c.append(title,el('p','Исследовательская карточка · не предложение к продаже','fine'));if(r.image)c.append(visual(r));const dl=el('dl',undefined,'detail-facts');for(const [k,v]of[['Район и тип по источнику',`${r.district} · ${kinds[r.kind]||r.kind}`],['Группа / бренд, не продавец',r.family?(r.family+(r.basis==='existing_seed_mapping'?' — прежнее сопоставление':' — кандидат из исходной базы')):'Ещё не установлена'],['Цена, наличие, комиссия','Актуальные условия не подтверждены'],['Регистрация и защита','По этой исходной записи не включены'],['Происхождение',`${data.source}, запись ${r.sourceRow}. ${r.id}`]]){const div=el('div');div.append(el('dt',k),el('dd',v));dl.append(div);}c.append(dl);const links=el('div',undefined,'actions');links.append(save(r));for(const [path,label]of[[`/mira/phuket/project/${r.slug}/`,'Постоянная ссылка ↗'],['/mira/documents/project-rules.html','Порядок проверки ↗']]){const a=el('a',label,'text-link');a.href=path;links.append(a);}c.append(links);$('detail').showModal();}
function card(r){const a=el('article',undefined,'project-card');a.dataset.project=r.slug;a.append(visual(r));const b=el('div',undefined,'card-body');b.append(el('p',`${r.district} · ${kinds[r.kind]||r.kind}`,'card-meta'));const h=el('h2'),link=el('a',r.name);link.href=`/mira/phuket/project/${r.slug}/`;link.onclick=e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.shiftKey)return;e.preventDefault();open(r);};h.append(link);b.append(h,el('p',r.family?`Группа по источнику: ${r.family}`:'Группа требует уточнения','card-family'));const actions=el('div',undefined,'card-bottom'),details=el('button','Открыть ↗','detail-button');details.onclick=()=>open(r);actions.append(details,save(r));b.append(actions);a.append(b);return a;}
function render(){if(!data)return;const list=filter(data.records,state(),selection),p=paginate(list,page);page=p.page;$('cards').replaceChildren(...p.records.map(card));$('count').textContent=`Найдено ${p.total} из ${data.count} исходных записей`;$('page-count').textContent=`${p.page} / ${p.pages}`;$('prev').disabled=p.page===1;$('next').disabled=p.page===p.pages;$('empty').hidden=!!p.total;selectionUI();url();}
function reset(){for(const id of ['q','district','kind'])$(id).value='';$('saved').setAttribute('aria-pressed','false');page=1;render();}
async function load(){request?.abort();const controller=new AbortController();request=controller;const timeout=setTimeout(()=>controller.abort(),10000);$('catalog-error').hidden=true;try{const response=await fetch('/mira/data/phuket.json',{signal:controller.signal,credentials:'omit'});if(!response.ok)throw Error('http');const text=await response.text();if(text.length>3000000)throw Error('size');const valid=validate(JSON.parse(text));if(request!==controller)return;data=valid;$('total').textContent=String(data.count);const district=$('district');while(district.options.length>1)district.remove(1);for(const d of [...new Set(data.records.map(r=>r.district))].sort()){const o=el('option',d);o.value=d;district.add(o);}for(const id of ['q','district','kind','reset','saved'])$(id).disabled=false;const u=new URL(location.href);$('q').value=(u.searchParams.get('q')||'').slice(0,200);for(const id of ['district','kind'])$(id).value=u.searchParams.get(id)||'';page=u.searchParams.get('page')||1;render();}catch(e){if(request!==controller)return;data=null;$('cards').replaceChildren();$('catalog-error').hidden=false;$('count').textContent='Каталог не загружен. Данные не подменяются.';for(const id of ['q','district','kind','reset','saved','prev','next','download-selection'])$(id).disabled=true;}finally{clearTimeout(timeout);}}
$('q').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{page=1;render();},100);};for(const id of ['district','kind'])$(id).onchange=()=>{page=1;render();};$('reset').onclick=reset;$('empty-reset').onclick=reset;$('retry').onclick=load;$('saved').onclick=()=>{$('saved').setAttribute('aria-pressed',String(!state().saved));page=1;render();};for(const [id,d]of[['prev',-1],['next',1]])$(id).onclick=()=>{page+=d;render();$('count').scrollIntoView({block:'center'});};$('download-selection').onclick=()=>{if(!data||!selection.size)return;const link=el('a');link.href=URL.createObjectURL(new Blob([brief(data.records,selection)],{type:'text/plain;charset=utf-8'}));link.download='MIRA-подборка-Пхукет.txt';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};function close(){ $('detail').close();lastFocus?.focus(); }$('close-detail').onclick=close;$('detail').addEventListener('cancel',e=>{e.preventDefault();close();});const mobile=matchMedia('(max-width:650px)');$('filter-options').open=!mobile.matches;mobile.addEventListener?.('change',()=>{$('filter-options').open=!mobile.matches;});load();}
